### ISSUE TITLE
希望能够增加支持deeplx的接口

### ISSUE THREAD

**Issue by SuperYuIuo** [ZGGSONG/STranslate#10]
基于该项目的搭建的deeplx，比deepl的免费api更好用一点。https://github.com/OwO-Network/DeepLX

**Comment by ZGGSONG** [comment]
这个项目代码我看过，都是模拟官方免费客户端的请求，和我另一个项目zggsong/deepl-api原理是一样的，他的response我这边是兼容的，你搭建好就可以直接调用。自带的公开接口我是写了一个ts版本放到deno上跑的，用的人太多了就被官方限制了。稳定还是要自己搭建接口，readme中我也推荐了三种方式，任选一种，然后配置一下就好。

**Comment by SuperYuIuo** [comment]
基于[https://github.com/OwO-Network/DeepLX项目](https://github.com/OwO-Network/DeepLX%E9%A1%B9%E7%9B%AE) 配置自建deeplx负载

1，创建文件夹，并保存nginx.conf文件

    events {
        worker_connections 1024;  # 增加 worker 连接数
        use epoll;  # 对于 Linux, 使用 epoll
        multi_accept on;
    }
    http {
        # 请求时间
        log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                '$status $body_bytes_sent "$http_referer" '
                '"$http_user_agent" "$http_x_forwarded_for" '
                'request_time=$request_time';
        access_log /dev/stdout main;
        error_log /dev/stderr info;
        # 基础设置
        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;
        # Gzip 压缩
        gzip on;
        gzip_vary on;
        gzip_proxied any;
        gzip_comp_level 6;
        gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
        proxy_cache_path /root/gpt/cache levels=1:2 keys_zone=my_cache:10m max_size=10g inactive=60m use_temp_path=off;

        upstream myapi {
            least_conn;  # 使用最少连接方法进行负载均衡
            keepalive 32;  # 启用 keepalive
            server x.x.x.x:1188 max_fails=3 fail_timeout=1800s;

        }

        server {
            listen 80;
            access_log /dev/stdout main;
            location /translate {
                proxy_pass http://myapi/translate;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;

                # 缓冲区设置
                proxy_buffers 16 16k;
                proxy_buffer_size 16k;
                proxy_cache my_cache;  # 启用缓存
            }
        }

        # 调整日志记录级别
        access_log off;
        error_log /var/log/nginx/error.log warn;
    }
2，使用 Docker 运行 Nginx 容器，并挂载该配置文件。在终端运行以下命令：

    docker run --name gpt --restart always -v /path/to/nginx.conf:/etc/nginx/nginx.conf:ro -v /path/to/cache:/root/gpt/cache -p 2080:80 -d nginx
其中，替换 /path/to/nginx.conf 为你保存 nginx.conf 文件的实际路径。

**Comment by SuperYuIuo** [comment]
如上，我自建的deeplx加了负载均衡，大概有40多个吧😁。今天用了一下您的软件，貌似deepl搭配我的deeplx反应不过来，只有谷歌翻译走了代理速度很快🫠

**Comment by ZGGSONG** [comment]
没太明白这一步负载均衡的操作，我试了一下OWO的项目，可以运行的。
![PixPin_2024-01-16_22-09-21](https://github.com/ZGGSONG/STranslate/assets/49741009/18d37da4-15c7-45cf-ba87-b5a15b36aa5c)
![PixPin_2024-01-16_22-09-40](https://github.com/ZGGSONG/STranslate/assets/49741009/8fc39121-30d3-4dfd-9f7c-2dfddbeb2fea)

**Comment by SuperYuIuo** [comment]
我也不确定噻，主要是我搭建的deeplx是用来搭配沉浸式翻译插件的，然后配置的这个负载就能正常使用。但是在你的软件中配置就不行，不是很确定为什么...

如果大佬有更优解决方案，麻烦告知一下0.0

**Comment by ZGGSONG** [comment]
我看你的nginx只是配了一个自定义域名，然后转发到最终的服务1188端口上，然后又套了层docker，那你服务在外面访问的话应该是`http://myapi:2080/translate`对吧，你填的是这个吗

**Comment by SuperYuIuo** [comment]
是的

**Comment by ZGGSONG** [comment]
> 我看你的nginx只是配了一个自定义域名，然后转发到最终的服务1188端口上，然后又套了层docker，那你服务在外面访问的话应该是`http://myapi:2080/translate`对吧，你填的是这个吗

不对，你的nginx没有监听外部域名，只监听了端口，但是像这样转发出来是否监听到本地网卡的2080上我也不太确定，你这个可能是本地dns解析导致的，你可以尝试用127.0.0.1:2080试试，或者把设置里面的禁用系统代理开开试试。都试一下吧。

**Comment by ZGGSONG** [comment]
> > 我看你的nginx只是配了一个自定义域名，然后转发到最终的服务1188端口上，然后又套了层docker，那你服务在外面访问的话应该是`http://myapi:2080/translate`对吧，你填的是这个吗
> 
> 不对，你的nginx没有监听外部域名，只监听了端口，但是像这样转发出来是否监听到本地网卡的2080上我也不太确定，你这个可能是本地dns解析导致的，你可以尝试用127.0.0.1:2080试试，或者把设置里面的禁用系统代理开开试试。都试一下吧。

我指的是我软件的设置，因为我会默认移动走系统代理，如果开了代理，并且用域名的话我也不知道是谁做的这个域名解析了

**Comment by ZGGSONG** [comment]
如果还有问题可以邮箱讨论，已经不属于这个软件范畴了
