### ISSUE TITLE
希望能添加设置GPT第三方接口的功能

### ISSUE THREAD

**Issue by xh542428798** [ZGGSONG/STranslate#100]
网上买的chatGPT api都是他们自己转发的地址，所以用的网址都是 http://www.xxx.xxx/v1/chat/completions
希望能支持这种自定义的GPT网站，并且还可以不要apikey的。
比如better ChatGPT项目：
![image](https://github.com/ZGGSONG/STranslate/assets/49368033/f2440698-c082-4413-9d52-e2591d3af369)

**Comment by xh542428798** [comment]
如果作者需要，我可以提供一个淘宝购买的apikey进行测试

**Comment by ZGGSONG** [comment]
支持的呀，你直接填进去试试就知道了

**Comment by xh542428798** [comment]
> 支持的呀，你直接填进去试试就知道了

我直接填进去，这个就会报错，但是相同的网址，我填在better ChatGPT里能正常使用（上面的截图）
![image](https://github.com/ZGGSONG/STranslate/assets/49368033/ddae1c8f-b96f-4119-894d-f6d9de66bc5c)

![image](https://github.com/ZGGSONG/STranslate/assets/49368033/91e6ceae-6831-4c1b-b91d-26e109eba543)

**Comment by xh542428798** [comment]
> ![image](https://private-user-images.githubusercontent.com/49741009/341478132-50980ec3-600a-432b-9711-e4c22d18cdf9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxNDI4NzMsIm5iZiI6MTcxOTE0MjU3MywicGF0aCI6Ii80OTc0MTAwOS8zNDE0NzgxMzItNTA5ODBlYzMtNjAwYS00MzJiLTk3MTEtZTRjMjJkMThjZGY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIzVDExMzYxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlMGZmNGI1ODcyNGRkYWYxYTA2MjVkYjhiZGMzMDM4N2ZlNmE5ZDc1NzhiMDdhYmFhNTg3YTg2MTQzMDVkZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ah0oaAoqt6f8EQZe3rjwqbpUNsxcL23BU3oHESm96v0)
> 
> 好吧，看了下代码，发现我在openai这个服务里面强制要求填apikey了，我下个版本移除掉这个限制🚫

大佬，下一个版本什么时候更新，您关闭了这个issue，还以为更新版本了😂😂😂

**Comment by ZGGSONG** [comment]
最近比较忙，写开源代码时间比较少。把几个没写完的功能完善下再发版本。你要着急，可以先clone最新的代码打包用😄

**Comment by xh542428798** [comment]
> 最近比较忙，写开源代码时间比较少。把几个没写完的功能完善下再发版本。你要着急，可以先clone最新的代码打包用😄

好的，谢谢大佬
