### ISSUE TITLE
能否限制翻译窗口每条显示的高度，翻译大量文本时候突然一下变得很长很难翻到

### ISSUE THREAD

**Issue by Rockytkg** [ZGGSONG/STranslate#101]
![image](https://github.com/ZGGSONG/STranslate/assets/102890277/e872ce9f-8f75-4584-847a-e081beb8d849)

**Comment by ZGGSONG** [comment]
![image](https://github.com/ZGGSONG/STranslate/assets/49741009/890b0549-92d9-46fa-b3dd-0c4e8fe89b1a)

目前是黄色部分整体滚动显示更多，然后每个可以折叠，如果做成红色部分有最大高度，每个服务单独滚动，你想直接看后面的服务就会比较困难，等于那个服务窗口都和输入部分的滚动效果一样

不过不管是黄色滚动还是红色部分滚动，对于你内容比较多的情况，都要往下滚动才能看多更多。没差呀，我感觉
