### ISSUE TITLE
希望添加游戏模式，防止游戏中误触发热键

### ISSUE THREAD

**Issue by 1783157448** [ZGGSONG/STranslate#107]
如题

**Comment by ZGGSONG** [comment]
软件支持手动屏蔽全局热键 右键托盘程序和常用设置页面都可以配置

**Comment by ZGGSONG** [comment]
![image](https://github.com/ZGGSONG/STranslate/assets/49741009/0497653f-056e-4e38-9db3-44ec5867cd2d)

新增可选全屏热键不触发
