### ISSUE TITLE
只要移动窗口 窗口就死掉变黑,界面没法操作

### ISSUE THREAD

**Issue by zrl2088** [ZGGSONG/STranslate#11]
![PixPin_2024-01-16_08-57-53](https://github.com/ZGGSONG/STranslate/assets/9834486/2cb8cb74-48b4-4873-a0c8-09e7196835af)

画面就啥都不显示了无论怎么用, 如果不移动窗口 都可以正常使用

**Comment by ZGGSONG** [comment]
你这是多屏幕嘛，有更详细的复现描述吗，我不太好确认是什么问题导致的

**Comment by zrl2088** [comment]
我是多屏幕, 两个屏幕  在主屏幕上只要拖动就是这个问题, 就是页面直接死在这儿 不显示了, 但是如果 盲操作按钮  还是可以点开比如 设置, 盲操作是可以点的

**Comment by zrl2088** [comment]
麻烦作者大大 看看是什么问题导致的 ,我系统 重装也没多久 ,  算是行系统把 ,  该装的也装了,  其他软件 没有这个问题 , 就这个软件有这个问题

**Comment by ZGGSONG** [comment]
![Maybe it's a bug](https://github.com/ZGGSONG/STranslate/assets/49741009/57fb37b5-6b71-48a9-a937-13a775114ce0)

就是我再开发使用过程中都没有遇到过这种问题。我不是放了两个版本嘛，你试试另一个大一点的(self-contained)版本，试试看还有没有这个问题。

**Comment by ZGGSONG** [comment]
> 麻烦作者大大 看看是什么问题导致的 ,我系统 重装也没多久 , 算是行系统把 , 该装的也装了, 其他软件 没有这个问题 , 就这个软件有这个问题

如果不拓展显示器，单显示器有没有这个问题

**Comment by zrl2088** [comment]
测试了 不扩展显示器  只用 一个  没有这个问题,  两个显示器就有这个问题

**Comment by ZGGSONG** [comment]
我修改了一些东西，打包了一下，可能能解决你出现的问题，可以试下。
[https://www.123pan.com/s/AxlRjv-dzVmA.html](https://www.123pan.com/s/AxlRjv-dzVmA.html)
提取码:
```txt
song
```
