### ISSUE TITLE
两个小细节/设置项，能否考虑下？

### ISSUE THREAD

**Issue by C1og** [ZGGSONG/STranslate#110]
1. 增加触发 `输入翻译` 功能时文本是否全选状态的开关
    -  使用场景：`输入翻译` 和 `划词翻译` 在功能上部分重叠，如果用户在触发“输入翻译”时，界面中的文本自动全选，用户即可直接进行输入翻译，从而在一定程度上实现功能上的合并
    - 好处：减少全局快捷键的占用以及记忆负担
2. 增加启用/禁用消息提示开关
    - ![image](https://github.com/ZGGSONG/STranslate/assets/44397460/364c7572-4bf4-413f-8457-444adbcf24a0)

**Comment by ZGGSONG** [comment]
1. 这条建议我感觉你的意思是想将`输入翻译`和`显示界面`功能合并吧, 不过确实很多时候我也是使用`显示界面`功能, 想要输入内容翻译才想起来在使用热键`Alt`+`A`来触发输入翻译以达到清除内容的效果. 这部分我调研一下, 如果大家用到的确实不多可以考虑后续更新成显示界面用户可选全选输入框内容, 也就达到了输入翻译差不多的效果
2. 这个开关下个版本加上去, 似乎不少人对这个提示信息有点意见 (当时没写过动画的我还研究半天 哈哈哈哈)
