### ISSUE TITLE
内置翻译服务用的是

### ISSUE THREAD

**Issue by toyo2333** [ZGGSONG/STranslate#111]
使用的是本地模型还是在线服务？ 

出于隐私相关的考量作出提问

**Comment by ZGGSONG** [comment]
分开说吧：
1. 翻译服务中除了ollama这个，其余均为云服务，内置本地服务为调用某海外知名翻译公司api
2. OCR中本地服务即PaddleOcr未完全离线服务，不联网，不过在首次下载软件后需要下载一下离线数据包
3. TTS本地服务未完全离线服务
