### ISSUE TITLE
能否添加持续OCR识别翻译功能？

### ISSUE THREAD

**Issue by MianJu28** [ZGGSONG/STranslate#112]
就是选定一片区域，持续或者按快捷键对这片区域里的文字进行OCR识别翻译，方便翻译游戏或者视频里的字幕。

**Comment by ZGGSONG** [comment]
这个需求我记得我以前有看到过一个开源项目专门解决这个痛点，不过现在不记得是哪个了。你可以再找找

另外视频字幕这个推荐 [沉浸式翻译](https://immersivetranslate.com)

**Comment by ZGGSONG** [comment]
> 持续或者按快捷键对这片区域里的文字进行OCR识别翻译
@MianJu28  https://github.com/TheJoeFin/Text-Grab 这个开源项目似乎能解决你这个需求
