### ISSUE TITLE
[FR] 增加热键：翻译剪贴板内容

### ISSUE THREAD

**Issue by Azona77** [ZGGSONG/STranslate#113]
### 痛点
- 我是从copy translator转过来的，copy translator最常用的功能是 `Ctrl+C+C` **翻译剪贴板内容并写入剪贴板**（相当于静默翻译），但STranslate并没有对应的功能；STranslate虽然可以监听剪贴板，但这样就影响了正常的复制粘贴，需要频繁手动切换。

### 需求
- 希望增加**翻译剪贴板内容**的热键，最便捷的方案是 `Ctrl+C+C` 这种形式（相当于正常复制后，只需要同位置的一次按键即可触发）
  - 理想的架构应该是 `A热键（Ctrl+C）` 触发正常复制， `B热键（Ctrl+C+C）` 触发翻译剪贴板内容，配合已有的选项可选是否复制到剪贴板；
  - 而不应是现在的“监听剪贴板”选项，将上述的  `复制和翻译的热键` 混在一起，每次需要正常复制粘贴时都需要手动开关

**Comment by ZGGSONG** [comment]
正常的功能触发是alt+d滑词热键触发翻译
监听剪贴板原本也只是网友对监听鼠标滑词后立即翻译的一个补充功能，他提了我就做了而已，这个不是原有设计的核心，核心功能是应该是选中文本，alt+d触发翻译！

**Comment by Azona77** [comment]
> 最佳的触发是鼠标选中文字热键触发翻译
> 
> 监听剪贴板原本也只是网友对监听鼠标滑词后立即翻译的一个补充功能，他提了我就做了而已，这个不是原有设计
> 
> 核心功能是应该是选中文本，alt+d触发翻译！

我以为 热键选项里的“划词翻译” 和 任务栏图标右键里的一样 是开关切换的😂到手关了，没想到是单次触发的形式
那就很完善了，需要定制Ctrl+C+C的用户自己用ahk触发划词翻译就好了
准备长期用了，不用装两个单独的翻译和OCR软件了，感谢大佬❤
