### ISSUE TITLE
OCR 服务能否支持火山OCR

### ISSUE THREAD

**Issue by kongwu-** [ZGGSONG/STranslate#114]
内置的Paddle和百度的，不支持多语言。

火山OCR服务速度很快，多语言支持很好，限流也比较宽松，希望可以支持一下

**Comment by ZGGSONG** [comment]
PaddleOCR自动选择支持识别中英文数字标点符号
另外手动切换支持日、韩语
百度支持很多，都在官网有介绍，普通版少一些，高精版多一些
并非不支持，只可能是你选择的恰好不在支持范围内

火山OCR这个我回头接入一下

**Comment by kongwu-** [comment]
> PaddleOCR自动选择支持识别中英文数字标点符号 另外手动切换支持日、韩语 百度支持很多，都在官网有介绍，普通版少一些，高精版多一些 并非不支持，只可能是你选择的恰好不在支持范围内
> 
> 火山OCR这个我回头接入一下

百度的确实可以，普通版做不到多语言自动识别（韩语），高精度没问题，效果很好。

刚又看了下火山的免费政策，现在是固定5000次（每账号）了，不太划算……希望作者可以考虑接入腾讯OCR或者腾讯图片翻译，每月固定免费配额，个人用户足够了。

| 厂商 | 服务              | 免费额度                 | 超出免费额度	  |
|----|-----------------|----------------------|----------|
| 火山 | 多语种 OCR（试用模式） | 共计 5000 次（每个账号赠送一次）	 |          |
| 腾讯 | 通用印刷体识别         | 1000次/月              | 0.15元/次  |
| 腾讯 | 图片翻译            | 1W次/月                | 0.045元/次 |

**Comment by kongwu-** [comment]
> > PaddleOCR自动选择支持识别中英文数字标点符号 另外手动切换支持日、韩语 百度支持很多，都在官网有介绍，普通版少一些，高精版多一些 并非不支持，只可能是你选择的恰好不在支持范围内
> > 火山OCR这个我回头接入一下
> 
> 百度的确实可以，普通版做不到多语言自动识别（韩语），高精度没问题，效果很好。
> 
> 刚又看了下火山的免费政策，现在是固定5000次（每账号）了，不太划算……希望作者可以考虑接入腾讯OCR或者腾讯图片翻译，每月固定免费配额，个人用户足够了。
> 
> 厂商	服务	免费额度	超出免费额度
> 火山	多语种 OCR（试用模式）	共计 5000 次（每个账号赠送一次）	
> 腾讯	通用印刷体识别	1000次/月	0.15元/次
> 腾讯	图片翻译	1W次/月	0.045元/次

不过百度这个高精度版，图片尺寸稍微大点，会提示 input oversize：
![image](https://github.com/ZGGSONG/STranslate/assets/7615848/94c7e310-d5b6-4e7a-a7ff-01eaf13d30a9)

**Comment by ZGGSONG** [comment]
> 刚又看了下火山的免费政策，现在是固定5000次（每账号）了，不太划算……希望作者可以考虑接入腾讯OCR或者腾讯图片翻译，每月固定免费配额，个人用户足够了。

ok

**Comment by ZGGSONG** [comment]
> > PaddleOCR自动选择支持识别中英文数字标点符号 另外手动切换支持日、韩语 百度支持很多，都在官网有介绍，普通版少一些，高精版多一些 并非不支持，只可能是你选择的恰好不在支持范围内
> > 火山OCR这个我回头接入一下
> 
> 百度的确实可以，普通版做不到多语言自动识别（韩语），高精度没问题，效果很好。
> 
> 刚又看了下火山的免费政策，现在是固定5000次（每账号）了，不太划算……希望作者可以考虑接入腾讯OCR或者腾讯图片翻译，每月固定免费配额，个人用户足够了。
> 
> 厂商	服务	免费额度	超出免费额度
> 火山	多语种 OCR（试用模式）	共计 5000 次（每个账号赠送一次）	
> 腾讯	通用印刷体识别	1000次/月	0.15元/次
> 腾讯	图片翻译	1W次/月	0.045元/次

腾讯通用印刷体识别目前就是支持的：
![image](https://github.com/ZGGSONG/STranslate/assets/49741009/36d15df5-5dd6-4719-9d85-b717ca46d757)

**Comment by kongwu-** [comment]
4K屏下，截图尺寸是否过大。百度、腾讯OCR服务经常会报图片过大，实际上截图选区并不大

![image](https://github.com/ZGGSONG/STranslate/assets/7615848/2f33b9a3-63a6-4c7e-82ae-b0db77ef045c)

**Comment by kongwu-** [comment]
> 4K屏下，截图尺寸是否过大。百度、腾讯OCR服务经常会报图片过大，实际上截图选区并不大
> 
> ![image](https://private-user-images.githubusercontent.com/7615848/347461211-2f33b9a3-63a6-4c7e-82ae-b0db77ef045c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MjQ1MDAsIm5iZiI6MTcyMDYyNDIwMCwicGF0aCI6Ii83NjE1ODQ4LzM0NzQ2MTIxMS0yZjMzYjlhMy02M2E2LTRjN2UtODJhZS1iMGRiNzdlZjA0NWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTBUMTUxMDAwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmVhZDAzZWJhNDIxNTA5ZWJhZjNmMDM5Yzc1Yjg4Njg0ZmM3MzM2NTgxNTU4NDE1YzZmZTFlZTY3Y2I2MjlkMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.cYcfFcR6leVvB6ihA_9KxUxuGC1U3lmVH2wVlI3Fkyc)

4K屏，缩放150%

**Comment by ZGGSONG** [comment]
这个我看下加一个压缩选项可不可以避免这样的问题

**Comment by ZGGSONG** [comment]
火山OCR这个效果不得不说真是稀烂
![image](https://github.com/user-attachments/assets/9e33353b-5681-48e6-b154-41c5c08887a7)

**Comment by kongwu-** [comment]
> 4K屏下，截图尺寸是否过大。百度、腾讯OCR服务经常会报图片过大，实际上截图选区并不大

可能好处是多国语言支持的还不错。。。

**Comment by kongwu-** [comment]
> 火山OCR这个效果不得不说真是稀烂 ![image](https://private-user-images.githubusercontent.com/49741009/348442454-9e33353b-5681-48e6-b154-41c5c08887a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMzkxNjMsIm5iZiI6MTcyMTAzODg2MywicGF0aCI6Ii80OTc0MTAwOS8zNDg0NDI0NTQtOWUzMzM1M2ItNTY4MS00OGU2LWIxNTQtNDFjNWMwODg4N2E3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDEwMjEwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjNDA0NTZhYzk2Njk4MDFlOTc1NDY3MDNjYjFkOWI0MGMwNzA4NzRmNTFkMzk4MjliOWQyNTgzNDg4Mjg3YjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xMtvJCodaZ7PHE9WbEbbK_W4IyV8dCMtyfYbB3al1H8)

可能好处是多国语言支持的还不错。。。
