### ISSUE TITLE
可否开发集成到snipdo的小插件

### ISSUE THREAD

**Issue by uniquMonte** [ZGGSONG/STranslate#115]
snipdo是一款插好用的工具软件，我想问下这个可否开发一个小插件，集成到snipdo上，这样通过鼠标取词就可调用翻译服务，而不需要每次都按快捷键翻译，可参考pot翻译软件开发的类似小插件，谢谢

**Comment by ZGGSONG** [comment]
老早之前试了一下，好像要成为会员才能打包成可执行文件一键导入

**Comment by ZGGSONG** [comment]
更新了一下文档先提供手动创建Snipdo插件的方式，后面我在打包成一键安装插件
[https://stranslate.zggsong.com/docs/invoke.html#%E9%9B%86%E6%88%90%E8%B0%83%E7%94%A8](https://stranslate.zggsong.com/docs/invoke.html#%E9%9B%86%E6%88%90%E8%B0%83%E7%94%A8)

**Comment by uniquMonte** [comment]
我按照教程一模一样设置之后，依然用不了啊，点击了之后弹出的是“x”

**Comment by ZGGSONG** [comment]
snipdo用的不多  不太清楚弹出"x"是啥意思，可否贴图或者gif呢

**Comment by uniquMonte** [comment]
就是点击了snipdo上的图标，没有正常弹出翻译软件的界面，而是显示一个x，表示没有调用成功

**Comment by uniquMonte** [comment]
刚在软件上改了下端口，现在可以调出来了，我之前没改软件上的端口，用的是默认的50020端口，我刚随便改了一个其它的端口，可以调出来了，问题已解决，谢谢，这软件做的不错！
