### ISSUE TITLE
[FR] OCR能否支持Doc2X

### ISSUE THREAD

**Issue by Menghuan1918** [ZGGSONG/STranslate#116]
能否增加Doc2X识别服务？其支持识别图片为公式和带格式的通用文本，并且个人用户每日有免费500次识别次数

官网：
https://doc2x.noedgeai.com

API文档：
https://noedgeai.feishu.cn/wiki/Qb1SwLBi5iz6cDkVyICcVBYgnRd

**Comment by ZGGSONG** [comment]
离线OCR使用的是[PaddleOCRSharp](https://gitee.com/raoyutian/PaddleOCRSharp)
本软件主要是作为方案整合
