### ISSUE TITLE
几个使用中的细节反馈

### ISSUE THREAD

**Issue by dlzmoe** [ZGGSONG/STranslate#117]
1. 关于【划词翻译】功能，在鼠标未处于选中状态时，运用 alt+d 快捷键亦可开启弹窗，并呈现上一次的划词内容。此情况不知是有意为之的设计还是存在漏洞。
2. 默认字体的大小感觉稍显偏大，可否增添调整字体大小的设置。

整体的使用体验非常棒，已向多位朋友进行推荐。

**Comment by ZGGSONG** [comment]
1. 因为划词翻译功能的逻辑是热键触发时模拟键盘`Ctrl`+`C`复制内容, 随后读取剪贴板最新的一次内容使用他进行翻译, 如果没有选中内容, 则会拿到剪贴板最新的结果进行翻译.
> 也许你会有疑问, 为什么不做一次对比, 如果是旧的内容就不取词翻译呢? 答: 因为有的时候会选中文本再次触发划词翻译, 有的时候你会忘了你上一次刚好翻译过这个内容.相信我这是经常出现的. 当然避免旧内容这部分逻辑软件也有, 放在了监听鼠标划词那个功能里, 那部分更加适合上述逻辑 [GetSelectedText](https://github.com/ZGGSONG/STranslate/blob/main/src/STranslate.Util/ClipboardUtil.cs#L21)、[GetSelectedTextDiff](https://github.com/ZGGSONG/STranslate/blob/main/src/STranslate.Util/ClipboardUtil.cs#L38)
2. 字体这个我也感觉有一点大哈哈哈哈哈, 一直没动力去改, 在等有缘人提 你既然提了 我后面就更新一下吧😂

很高兴能帮到你，感谢分享😊

**Comment by ZGGSONG** [comment]
079da17
