### ISSUE TITLE
一些使用反馈及建议

### ISSUE THREAD

**Issue by SharkSpancil** [ZGGSONG/STranslate#122]
非常感谢作者制作了这款翻译软件！
软件界面美观，响应迅速，在课题组广受好评。
在软件使用过程中，遇到了1个问题，2个提升效率的建议，向作者反馈。

问题：移除换行功能使用正常，但无法识别2个段落间的换行，最终并为1行。翻译结果中无法区别前1个段落的结尾和后1个段落的开始。

建议1：更多的界面排版选择，比如移除原文框。
原因：屏幕大小有限，可以增加阅读效率。使用了翻译软件，多数情况都不再看原文，除非对翻译结果有疑问。
![图片2](https://github.com/ZGGSONG/STranslate/assets/175198274/7b4394ba-acf3-41e2-839e-b87da4e8ea96)

建议2：更多的翻译界面显示选择，可以固定翻译界面大小。翻译界面可以被其他应用覆盖，通过切换窗口再次置到最前。
原因：写作过程中会使用到多个窗口，频繁来回切换。如绘图软件、word、浏览器、PDF阅读器、Endnote以及翻译软件，翻译界面不再是消失或置顶，能避免二次翻译。翻译界面在内容较少时，窗口高度会变化，无法每次都达到设定的最大值，有窗口伸缩的动画，很丝滑，也很优美。但使用中发现动画分散注意力。

其他：增加白名单模式。使翻译功能仅对某些软件生效，如PDF阅读器。
“`”可以单独设置为翻译快捷键，但“Ctrl”不行。单击“Ctrl”作为翻译快捷键可以被考虑。

感谢作者对软件付出的努力！
祝您生活学习工作顺利！

**Comment by ZGGSONG** [comment]
问题：
这个我好像没有复现

- 翻译后换行

https://github.com/ZGGSONG/STranslate/assets/49741009/cb22e276-48ee-4153-bc72-52c8c8de0681

- 取词时换行

https://github.com/ZGGSONG/STranslate/assets/49741009/17a0525b-2585-4d8d-814a-374005be1573

建议：
1. 软件内快捷键 `Ctrl`+`Shift`+`A`可以控制显示隐藏输入框，文档中有说明
<img width="1624" alt="image" src="https://github.com/ZGGSONG/STranslate/assets/49741009/7ad88c15-dce8-434e-bc19-094d9945b870">

2. 当前最新版就支持失去焦点后不隐藏界面，并且可选显示关闭按钮 [1.1.6.704](https://github.com/ZGGSONG/STranslate/releases/tag/1.1.6.704) #104 
> 其实这个我是真不想做，我的目标其实就是即用即走，但是现在用的越来越多，就加上了，设置页面配置保存一下就生效

其他：
单个热键作为快捷键的话不允许设置ModifierKey(Shift、Ctrl 或 Alt)按键作为全剧热键，不然你的切换页面(Alt+Tab)，全选(Ctrl+A)，复制粘贴，大写(Shift+字母)怎么搞，单个按键设置热键其实也不太推荐，容易误触，不过有的人有些部分按键用的不多，还是加上了，用户自行取舍，但是修饰键不开放单个热键

感谢对本软件的喜欢🎉🎉🎉
