### ISSUE TITLE
作者大佬好，我想问一下Gemini翻译服务用的是啥模型？

### ISSUE THREAD

**Issue by uniquMonte** [ZGGSONG/STranslate#126]
我在使用Gemin翻译服务的时候，里面没有设置具体模型的地方，Gemini有三个免费模型：Gemini 1.5 Flash，Gemini 1.5 Pro，Gemini 1.0 Pro，所以我在使用的时候，到底用的是哪个模型，可否增加选择项或者自定义这个具体的模型，由用户指定，谢谢！

**Comment by ZGGSONG** [comment]
![image](https://github.com/user-attachments/assets/feb923dd-ecb3-4537-a0da-85ad5a94157d)

这个是最早写的，也没啥人用，就一直没更新，我回头去看看，把模型切换加上😂

**Comment by uniquMonte** [comment]
好的，谢谢
