### ISSUE TITLE
[BUG] 在福昕PDF阅读器中划词翻译不可用

### ISSUE THREAD

**Issue by shaopeijie** [ZGGSONG/STranslate#13]
福昕PDF阅读器快捷键划词翻译和连续划词翻译均无法正常使用，阅读器版本12.0.125.13054, 系统版本win11 22H2

**Comment by ZGGSONG** [comment]
划词翻译是使用剪贴板作中转有的pdf不允许复制，你可以先看看是不是这个问题导致的

**Comment by ZGGSONG** [comment]
> 划词翻译是使用剪贴板作中转有的pdf不允许复制，你可以先看看是不是这个问题导致的

另外有的软件是以管理员权限启动的，这个时候如果stranslate是普通用户启动也会无法获取划词内容，如果是这种情况，选择设置管理员启动后重启即可

**Comment by shaopeijie** [comment]
> 划词翻译是使用剪贴板作中转有的pdf不允许复制，你可以先看看是不是这个问题导致的

已确认PDF内容允许复制。划词后按ctrl+c，选中内容出现在剪贴板里(win+v)。另外我发现当我按住ctrl+c后，pdf软件右下角会弹闪现一个对话框提示信息为“正在准备...”，有没有可能PDF软件优先捕捉到了剪切板事件？

**Comment by ZGGSONG** [comment]
close with [1.0.4.122](https://github.com/ZGGSONG/STranslate/releases/tag/1.0.4.122)
