### ISSUE TITLE
大佬会考虑增加截图和截图置顶吗 那样的话 tim截图功能基本可以弃用了

### ISSUE THREAD

**Issue by a872675986** [ZGGSONG/STranslate#130]
![image](https://github.com/user-attachments/assets/03ba7433-b02b-4164-88f6-e5bd740608c2)
有截图 保存和复制 和截图置顶啥的 基本是图片复制类都齐全了

**Comment by ZGGSONG** [comment]
有截图复制保存。没有置顶，这个也没有计划去做，本软件的重心是翻译，截图功能推荐snipaste
