### ISSUE TITLE
翻译成日语后 插入结果  异常

### ISSUE THREAD

**Issue by amaoo** [ZGGSONG/STranslate#131]
Ver： 1.1.6.704

![bug](https://github.com/user-attachments/assets/00f8e380-ff83-4305-a40e-71fcd8beb256)

**Comment by ZGGSONG** [comment]
贴一下日志内容

**Comment by amaoo** [comment]
这个没有错误日志，可能需要你那重新打个包

**Comment by ZGGSONG** [comment]
> 只是插入了一部分，并且没有恢复原内容

看了下恢复那个逻辑只在替换翻译里面写了

**Comment by amaoo** [comment]
基本上必现，而且是日语会出现，目前发现 slack 有这个问题

**Comment by amaoo** [comment]
百度翻译，腾讯的插入也都不全

**Comment by ZGGSONG** [comment]
ok，我看下什么问题，不管哪个翻译，底层都是一个接口去调用键盘模拟输出的

**Comment by amaoo** [comment]
好像就日语出现这个问题，试了英语，韩文，法语都没问题

**Comment by ZGGSONG** [comment]
![动画](https://github.com/user-attachments/assets/5f26647f-6427-4e9c-bbaa-5eecc69613b3)

我感觉你这个不是代码层面的问题，看着像语言包或者什么编码问题，你装的是什么版本的系统，你那边输出的日文有点不太对劲。输出的日文都不是原来的翻译内容了。

**Comment by amaoo** [comment]
> 版本	Windows 11 专业版
版本号	23H2
安装日期	‎2024/‎5/‎24
操作系统版本	22631.3880
体验	Windows Feature Experience Pack 1000.22700.1020.0

![image](https://github.com/user-attachments/assets/3b6d5cd2-f252-4bd2-8b8e-2626aac5b447)

**Comment by amaoo** [comment]
开机后 测试了下，正常了，使用一段时间后可能又会出现这个问题

**Comment by amaoo** [comment]
插入结果应该调用系统的粘贴操作，与语言包关系不大吧

**Comment by ZGGSONG** [comment]
> ok，我看下什么问题，不管哪个翻译，底层都是同一个接口去调用键盘模拟输出的

> 插入结果应该调用系统的粘贴操作，与语言包关系不大吧

是模拟键盘输出

**Comment by amaoo** [comment]
>ok，我看下什么问题，不管哪个翻译，底层都是同一个接口去调用键盘模拟输出的

不好意思，没太注意 
插入结果使用复制粘贴的方式去做的话是不是可以修复这个问题

**Comment by ZGGSONG** [comment]
不能这么干，流式输出像openai这种的  复制粘贴方式就不太好， 用户体验上就是等了好半天也不知道干啥了

**Comment by amaoo** [comment]
:sweat_smile: 
可以等翻译 流式输出 完成后，再去调用复制粘贴

**Comment by ZGGSONG** [comment]
你这个问题我再看看吧

**Comment by amaoo** [comment]
日语的语言包已经删除，翻译成日语后插入还是会出现这个问题

**Comment by amaoo** [comment]
> 在处理输入时，InputSimulator.Keyboard.TextEntry 方法可能会出现与日语字符的编码或文本分割相关的问题，尤其是在处理全角字符（例如日语中的字符）时。
> 你遇到的情况是由字符串分割或输入字符顺序的问题导致的。可能的原因是输入流在处理非 ASCII 字符时没有正确地保持字符顺序，特别是在 TextEntry 中连续输入字符时。

我这里试了下 
1. 逐字符输入
将整行文本拆分为单个字符，然后使用 TextEntry 方法输入每个字符。
2. 模拟键盘输入的 Unicode 码
有时直接使用 TextEntry 会忽略字符的具体编码，特别是多字节字符。可以尝试通过发送 Unicode 字符的方式进行输入，而不是依赖文本输入函数。

两种都不行

**Comment by ZGGSONG** [comment]
edge可以复现是吧，我最近比较忙，回头调试看看，能复现才有调试的可能。

那个键盘模拟库好像很老了，我看都是自己用着发现问题自己改一点然后接着用😂

**Comment by amaoo** [comment]
版本 128.0.2739.79 (正式版本) (64 位)
windows版本: 22631.4169

模拟键盘输入的程序  在edge 和 slack 测试正常

STranslate 在 edge 时好时坏，slack 必现（我晚上回去换台电脑试试）

**Comment by amaoo** [comment]
尴尬了，我家里的电脑也没复现

**Comment by amaoo** [comment]
我就先关闭这个issue了，不具有普遍性，明天看看两电脑有啥区别

**Comment by amaoo** [comment]
@ZGGSONG 
有点懵逼，删除软件，清空 `C:\Users\xxx\AppData\Local\STranslate` 里面的配置，
然后重新安装再测试，发现正常了.....

然后过一会，slack 还是正常，edge又复现了
阿西吧，就这样， 后续其他人出现这种问题  建议清空配置项重试

对了，在 导入导出 那能否加上  一键恢复所有默认或者清空所有配置
