### ISSUE TITLE
大佬就可以看一下

### ISSUE THREAD

**Issue by ywyjcloud** [ZGGSONG/STranslate#133]
https://github.com/user-attachments/assets/7a24b759-36d9-4128-83fc-852d041f1d9a

**Comment by ZGGSONG** [comment]
发现只有在软件有其他窗口打开并且获取焦点的情况下截图窗口的鼠标移动事件没法持续监听导致的，代码已提交下个版本发布

**Comment by uniquMonte** [comment]
这种情况我最近也碰到了

**Comment by ywyjcloud** [comment]
好的，感谢大佬的关注
