### ISSUE TITLE
ollama运行成功,但验证失败，请求错误：由于目标计算机积极拒绝，无法连接。（localhost:11443）

### ISSUE THREAD

**Issue by ttuuoo** [ZGGSONG/STranslate#134]
ollama运行成功,但验证失败，请求错误：由于目标计算机积极拒绝，无法连接。（localhost:11443）
如图：
![2024-07-19_133815](https://github.com/user-attachments/assets/cedafe40-4f43-433b-ab3b-ac17fb69e66e)

**Comment by ZGGSONG** [comment]
端口 [ollama](https://github.com/ollama/ollama?tab=readme-ov-file#generate-a-response)

**Comment by ttuuoo** [comment]
> 端口 [ollama](https://github.com/ollama/ollama?tab=readme-ov-file#generate-a-response)

刚刚我也发现了，尴尬了。。。。。。。

**Comment by ZGGSONG** [comment]
水印里打错了  我改下代码把
