### ISSUE TITLE
增量翻译+鼠标划词bug

### ISSUE THREAD

**Issue by JacobLee713** [ZGGSONG/STranslate#137]
当划词翻译开启时，打开增量翻译，这个时候再使用划词，当前的翻译内容会被替换为新的划词内容，不会作为增量内容被合并翻译。不知道是属于软件逻辑还是bug呢。另外希望作者大佬可以增加一个增量翻译的热键，科研狗论文翻页的时候真的很需要😭

**Comment by ZGGSONG** [comment]
1. 看了下代码，监听鼠标划词这部分忘了加增量判断，加一下就好
2. 增量翻译启用禁用增加一个软件内热键吧

**Comment by JacobLee713** [comment]
感谢作者大大！！
