### ISSUE TITLE
[bug]截图翻译快捷键设置错误

### ISSUE THREAD

**Issue by shenzhibuqin** [ZGGSONG/STranslate#14]
将快捷键设置为如下情况
![image](https://github.com/ZGGSONG/STranslate/assets/44872392/ae20bee6-ed4c-449a-ad57-67856175e42a)
再次打开设置，截图会自动恢复快捷键
![image](https://github.com/ZGGSONG/STranslate/assets/44872392/9a77de2c-5c65-45c3-bf10-2d6fdfb71d30)
修改也会自动恢复
![image](https://github.com/ZGGSONG/STranslate/assets/44872392/4f8cf83f-4e4b-4f2f-9648-df616eb524cb)
![image](https://github.com/ZGGSONG/STranslate/assets/44872392/8403066b-b1aa-41a4-9568-246a008a06c6)

**Comment by ZGGSONG** [comment]
可能半夜写代码眼花了，我晚点排查一下

**Comment by ZGGSONG** [comment]
不过建议把配置备份一下后删除试试再开软件配置快捷键，新增的可能会有点影响(没测试过)

**Comment by shenzhibuqin** [comment]
> 如果你是旧版升级上来的，建议把配置备份一下后删除试试再开软件配置快捷键，新增的可能会有影响

直接用的最新版😁

**Comment by ZGGSONG** [comment]
> > 如果你是旧版升级上来的，建议把配置备份一下后删除试试再开软件配置快捷键，新增的可能会有影响
> 
> 直接用的最新版😁

好吧，可能眼花了我排查一下吧

**Comment by ZGGSONG** [comment]
> > > 如果你是旧版升级上来的，建议把配置备份一下后删除试试再开软件配置快捷键，新增的可能会有影响
> > 
> > 
> > 直接用的最新版😁
> 
> 好吧，可能眼花了我排查一下吧

截图翻译快捷键输入框调错了划词翻译的方法，导致的问题，确实眼花，下个版本打包修复🫡

**Comment by ZGGSONG** [comment]
close with [1.0.4.122](https://github.com/ZGGSONG/STranslate/releases/tag/1.0.4.122)
