### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by ywyjcloud** [ZGGSONG/STranslate#140]
1. 设置里面添加一个自动单词发音的选项
2. 那个读音的话，微软的好像不太好弄，这方面也不是很懂，自带的读音有点生硬

**Comment by ZGGSONG** [comment]
tts服务，哪家好用，你可以用用推荐，我来适配。这样啥都没有，我很茫然😶

**Comment by ZGGSONG** [comment]
自动发音也是需要tts服务来驱动的，系统自带的那个是根拉，关键不用配置，可以直接用
