### ISSUE TITLE
出现问题

### ISSUE THREAD

**Issue by xinxuezi** [ZGGSONG/STranslate#142]
你好，这个请问一下，这个出现
请求超时: The request was canceled due to the configured HttpClient.Timeout of 10 seconds elapsing.
该怎么办吗？

**Comment by xinxuezi** [comment]
![image](https://github.com/user-attachments/assets/16419530-ee78-479b-b01d-84eb0bcc47e8)

**Comment by xinxuezi** [comment]
这个该怎么解决

**Comment by ZGGSONG** [comment]
#141
