### ISSUE TITLE
使用有截图功能的错误

### ISSUE THREAD

**Issue by DrinkingHook** [ZGGSONG/STranslate#143]
![P20240728-140211.jpg](https://github.com/user-attachments/assets/d0b8a13d-739b-4be3-80d2-02a7d5e7286e)

软件版本:1.1.6.704
电脑:拯救者
系统:windows11
出现频率:偶尔
现象:全白(如图所示微泛黄)和泛白
说明:在我更新联想驱动包括bios之前是可以用的，可能是更新联想驱动导致的，但是在更新后正常使用了一段时间，有大概十分钟就完全不能使用了。(全白是更新驱动后出现)

**Comment by ZGGSONG** [comment]
估计是驱动的问题，截图的实现逻辑很简单，截一张当前桌面的作为背景盖在桌面上，然后选区而已，本质上就俩控件，控件显示不正常那很有可能就是你驱动的锅。
