### ISSUE TITLE
我在使用 STranslate 时收到错误消息

### ISSUE THREAD

**Issue by Code6306** [ZGGSONG/STranslate#145]
![Screenshot 2024-07-28 224956](https://github.com/user-attachments/assets/345a360d-8247-4ad4-8e8d-616623fa0f6a)
我收到此消息“OCR失败：离线数据不完整”，但我不知道如何修复它

**Comment by ZGGSONG** [comment]
自1.1.4.523版本以后分离PaddleOCR依赖以及模型数据，极大降低升级成本软件本体压缩后仅20MB左右
但需要首次下载需要到设置里面PaddleOCR配置页面点击一次下载数据包！
https://github.com/ZGGSONG/STranslate/releases/tag/1.1.4.523

![image](https://github.com/user-attachments/assets/95cdc572-11a9-4efe-8148-ee7bfe705d1c)
