### ISSUE TITLE
恳求添加“谷歌OCR"服务，让用户自行添加api

### ISSUE THREAD

**Issue by elfcute** [ZGGSONG/STranslate#147]
![image](https://github.com/user-attachments/assets/b6677192-0998-41fb-8bc0-c93d1b87142a)
谷歌ocr的识别超强
求大佬添加一个谷歌ocr服务，这样用户就可以自行输入谷歌ocr的apikey来配置了，球球了

**Comment by ZGGSONG** [comment]
gcp？我没有账号呀

**Comment by elfcute** [comment]
> gcp？我没有账号呀

我给你提供一个测试的，我发你邮箱。

**Comment by ZGGSONG** [comment]
ok 谢谢

**Comment by elfcute** [comment]
> ok 谢谢

大佬 我已经发给你邮箱了，期待早日上线

**Comment by elfcute** [comment]
![image](https://github.com/user-attachments/assets/0c0c2581-a3fc-4e59-90e9-fb721876480b)
兄弟看邮箱，我把账号发给你了，你登录看看要哪些信息。
还有我自己做的谷歌ocr油猴脚本你参考一下调用
