### ISSUE TITLE
关于官方gemini的问题

### ISSUE THREAD

**Issue by elfcute** [ZGGSONG/STranslate#148]
![image](https://github.com/user-attachments/assets/999f9da3-e053-4ff7-a80e-bf85ce5a4661)
如图，gemini模型无法自定义模型。
系统自带是‘https://generativelanguage.googleapis.com’，我想请问一下这个默认模型是什么模型？是gemini-1.5-pro-latest吗？

我看官方接口自定义模型请求是这样的，比如我想使用gemini-1.5-pro-lastest，接口地址就填写为‘https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-pro-latest’，但是目前STranslate中,我这样填写接口也改变不了自定义模型。（因为我模型即使随便填写比如’gemini-1.5-pro-latestopwuiw'这种一看就是无效的模型，竟然还能测试成功。）

或者是可以添加一个openai一样的自定义模型输入选项。当然通过接口调整也是可以的。

**Comment by elfcute** [comment]
补充截图
![image](https://github.com/user-attachments/assets/ef3f9926-1cf9-4c3d-abfa-b9060a8661b1)
即使模型名随便写，点击验证，也能成功。说明目前STranslate无法通过接口来实现自定义请求模型，或者是我的使用方法有错误吗？

**Comment by ZGGSONG** [comment]
#126  (82f6036cebcd21435cf213a4de550531f6a73c17)

已经适配还未发布

**Comment by ZGGSONG** [comment]
> 即使模型名随便写，点击验证，也能成功。说明目前STranslate无法通过接口来实现自定义请求模型，或者是我的使用方法有错误吗？

验证按钮是检查接口返回结果中HttpCode是否为200，Google 接口返回的是成功的就会显示验证成功
> 一般都要填key等校验信息，该方式主要为了验证key是否正确，一般服务api 验证key成功了httpcode都会返回200

**Comment by elfcute** [comment]
> #126 ([82f6036](https://github.com/ZGGSONG/STranslate/commit/82f6036cebcd21435cf213a4de550531f6a73c17))
> 
> 已经适配还未发布

欧克欧克 期待一手下一版本
