### ISSUE TITLE
PaddleOCR

### ISSUE THREAD

**Issue by chibuhu** [ZGGSONG/STranslate#149]
内置PaddleOCR下载数据包后只能使用一次，重启机器后提示
OCR失败: 离线数据不完整
然后又要下载一遍才能正常使用

**Comment by ZGGSONG** [comment]
退出软件后执行一次根目录的 `cleanocr.bat` 后重新下载再试试

**Comment by chibuhu** [comment]
不行，重启后有需要重新下载

**Comment by ZGGSONG** [comment]
你使用管理员权限下载的还是普通用户下载的，推荐别勾选管理员权限打开后下载数据包，部分人遇到问题管理员权限下载后普通用户无法读取的问题(可能)，该问题我目前无法复现，你可以先尝试看是否可行

**Comment by qingmeng006** [comment]
我是在软件安装目录运行，这样可以解决ocr重复下载的问题，但每次都需要先打开安装目录，再运行STranslate太不方便，期待作者可以完善。我发现问题的过程如下（希望对作者解决问题能够提供帮助）：在其他目录（非安装目录）建了个bat文件用于快速打开STranslate软件，但只要通过bat打开软件都会提示：OCR离线数据不完整。如果在软件的安装目录打开软件OCR则不会有问题，所有是不是软件安装包的STranslate.exe文件里是不是有必须在安装目录执行的程序？

**Comment by elfcute** [comment]
> 我是在软件安装目录运行，这样可以解决ocr重复下载的问题，但每次都需要先打开安装目录，再运行STranslate太不方便，期待作者可以完善。我发现问题的过程如下（希望对作者解决问题能够提供帮助）：在其他目录（非安装目录）建了个bat文件用于快速打开STranslate软件，但只要通过bat打开软件都会提示：OCR离线数据不完整。如果在软件的安装目录打开软件OCR则不会有问题，所有是不是软件安装包的STranslate.exe文件里是不是有必须在安装目录执行的程序？

可以试着重新卸载重装sstranslate

**Comment by qingmeng006** [comment]
> > 我是在软件安装目录运行，这样可以解决ocr重复下载的问题，但每次都需要先打开安装目录，再运行STranslate太不方便，期待作者可以完善。我发现问题的过程如下（希望对作者解决问题能够提供帮助）：在其他目录（非安装目录）建了个bat文件用于快速打开STranslate软件，但只要通过bat打开软件都会提示：OCR离线数据不完整。如果在软件的安装目录打开软件OCR则不会有问题，所有是不是软件安装包的STranslate.exe文件里是不是有必须在安装目录执行的程序？
> 
> 可以试着重新卸载重装sstranslate

重装了好几次，还是不行。必须在安装目录内打开软件

**Comment by ZGGSONG** [comment]
> 我是在软件安装目录运行，这样可以解决ocr重复下载的问题，但每次都需要先打开安装目录，再运行STranslate太不方便，期待作者可以完善。我发现问题的过程如下（希望对作者解决问题能够提供帮助）：在其他目录（非安装目录）建了个bat文件用于快速打开STranslate软件，但只要通过bat打开软件都会提示：OCR离线数据不完整。如果在软件的安装目录打开软件OCR则不会有问题，所有是不是软件安装包的STranslate.exe文件里是不是有必须在安装目录执行的程序？

我并没有做这种检测，代码是开源的，你甚至可以直接搜那串报错代码的位置，就是检查最终执行文件所在目录的那几个文件是否存在，不过我没有试过用bat启动会不会对底层代码过去软件目录有无影响，我明天试试。

创建快捷方式不就行了，我一般也是这么做，或者固定到开始菜单。另外如果你没有软件配置(第一次运行，或者说就是用户appdata/local没有stranslate这个配置目录)就会自动创建一个桌面快捷方式。你当初第一次下载运行的时候应该发现了。

**Comment by chibuhu** [comment]
昨晚看到qingmeng006的解决办法，今早开机直接从软件目录打开软件，PaddleOCR正常了，平常我都是将好多软件放在一个批处理里启动的。明天试试将软件属性里的管理员身份运行勾上用批处理启动看看

**Comment by ZGGSONG** [comment]
> 我并没有做这种检测，代码是开源的，你甚至可以直接搜那串报错代码的位置，就是检查最终执行文件所在目录的那几个文件是否存在，不过我没有试过用bat启动会不会对底层代码获取软件目录有无影响，我明天试试。

破案了  bat启动后 `Environment.CurrentDirectory` 获取到的路径是bat所在目录导致读取ocr相关文件时出错，感谢@qingmeng006 我来看看如何避免这个问题

ps: 起码有三四个人提出过这个错，我始终无法复现，难道都是建bat去启动软件嘛！

**Comment by ZGGSONG** [comment]
> 昨晚看到qingmeng006的解决办法，今早开机直接从软件目录打开软件，PaddleOCR正常了，平常我都是将好多软件放在一个批处理里启动的。明天试试将软件属性里的管理员身份运行勾上用批处理启动看看

如果你们都是批处理导致的该问题，那就说明应该不是我猜测的权限问题了，因为权限那个我换了好多台电脑始终无法复现。都自闭了🤣

**Comment by chibuhu** [comment]
勾了用p启动也不行，直接添加自启动了
