### ISSUE TITLE
移除谷歌翻译后，不能重新添加回来

### ISSUE THREAD

**Issue by iridescentGray** [ZGGSONG/STranslate#15]
移除谷歌翻译后，不能重新添加回来

![Snipaste_2024-01-19_11-45-44](https://github.com/ZGGSONG/STranslate/assets/24296497/1154e561-6fa5-4936-96cf-a836d9541197)

**Comment by iridescentGray** [comment]
因为不支持调整顺序，我想让baidu在前面，所以移除掉了google，但是发现弄不回来了

**Comment by ZGGSONG** [comment]
1. 调整顺序按住服务列表前面三条横杠处拖动即可
2. 移除掉只要没保存点击撤销就行，保存才会写入本地文件，撤销会再读一遍本地配置。如果你已经保存了，想找回软件自带的初始化的几个api，双击软件目录里的`CleanCache.bat`再打开软件即可重新初始化了
3. 谷歌api那个属于免费api与自带的deeplx，爱词霸一样，不属于官方服务，名字图标均可自定义

**Comment by ZGGSONG** [comment]
> 因为不支持调整顺序，我想让baidu在前面，所以移除掉了google，但是发现弄不回来了

你要是只想要那个api，源代码里搜索deno.dev就能找得到

**Comment by iridescentGray** [comment]
1
