### ISSUE TITLE
第三方 deepl 接口验证失败

### ISSUE THREAD

**Issue by dlzmoe** [ZGGSONG/STranslate#150]
用的是 linux.do 的 deepl 接口，在这里验证失败，不清楚是什么原因。

如果需要测试，可以联系我 anghunk@gmail.com

**Comment by ZGGSONG** [comment]
1. 接口是否满足服务接口要求
2. 怎么填写的接口
3. 具体报什么错

**Comment by dlzmoe** [comment]
@ZGGSONG 

key和接口地址都是linxudo提供的

![image](https://github.com/user-attachments/assets/dc7b78f0-357d-447f-8f7c-ace368b0b51c)

在沉浸式翻译中是可以使用的，只需要填一个url地址

![image](https://github.com/user-attachments/assets/7a6b3ac9-5252-44ad-9fbf-2f3a6d9e44c0)

**Comment by elfcute** [comment]
> @ZGGSONG
> 
> key和接口地址都是linxudo提供的
> 
> ![image](https://private-user-images.githubusercontent.com/65840178/354091178-dc7b78f0-357d-447f-8f7c-ace368b0b51c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0OTUwNTQsIm5iZiI6MTcyMjQ5NDc1NCwicGF0aCI6Ii82NTg0MDE3OC8zNTQwOTExNzgtZGM3Yjc4ZjAtMzU3ZC00NDdmLThmN2MtYWNlMzY4YjBiNTFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDA2NDU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhNGViMzFlMjE0OWMyNmUyZmJlZGE0YzA2MzFlMzhiZGRmNDIzN2Q4ODUxMzQ5OWVmMGZlZmQ4NjhlZDhlMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.otDbOpbyKFTWpFURs_2RK8Aqr19s9k39LP61mnhdvPw)
> 
> 在沉浸式翻译中是可以使用的，只需要填一个url地址
> 
> ![image](https://private-user-images.githubusercontent.com/65840178/354091573-7a6b3ac9-5252-44ad-9fbf-2f3a6d9e44c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0OTUwNTQsIm5iZiI6MTcyMjQ5NDc1NCwicGF0aCI6Ii82NTg0MDE3OC8zNTQwOTE1NzMtN2E2YjNhYzktNTI1Mi00NGFkLTlmYmYtMmYzYTZkOWU0NGMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDA2NDU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyMTRlMDdhNzY2MGNlZDBiMWVlYjlkNjc1Yzk5ODdhZjQ5MzU1MDgyNDI3MjgzZDFhMDA5MzFiY2MyNDIwNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LBhJ3sFTvEPJMXONJGTah3EQoAU3h_CCWnMp4drjR4k)

逆天 你这个是deeplx，不是deepl

**Comment by dlzmoe** [comment]
> > @ZGGSONG
> > key和接口地址都是linxudo提供的
> > ![image](https://private-user-images.githubusercontent.com/65840178/354091178-dc7b78f0-357d-447f-8f7c-ace368b0b51c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0OTUwNTQsIm5iZiI6MTcyMjQ5NDc1NCwicGF0aCI6Ii82NTg0MDE3OC8zNTQwOTExNzgtZGM3Yjc4ZjAtMzU3ZC00NDdmLThmN2MtYWNlMzY4YjBiNTFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDA2NDU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhNGViMzFlMjE0OWMyNmUyZmJlZGE0YzA2MzFlMzhiZGRmNDIzN2Q4ODUxMzQ5OWVmMGZlZmQ4NjhlZDhlMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.otDbOpbyKFTWpFURs_2RK8Aqr19s9k39LP61mnhdvPw)
> > 在沉浸式翻译中是可以使用的，只需要填一个url地址
> > ![image](https://private-user-images.githubusercontent.com/65840178/354091573-7a6b3ac9-5252-44ad-9fbf-2f3a6d9e44c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0OTUwNTQsIm5iZiI6MTcyMjQ5NDc1NCwicGF0aCI6Ii82NTg0MDE3OC8zNTQwOTE1NzMtN2E2YjNhYzktNTI1Mi00NGFkLTlmYmYtMmYzYTZkOWU0NGMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAxVDA2NDU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyMTRlMDdhNzY2MGNlZDBiMWVlYjlkNjc1Yzk5ODdhZjQ5MzU1MDgyNDI3MjgzZDFhMDA5MzFiY2MyNDIwNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LBhJ3sFTvEPJMXONJGTah3EQoAU3h_CCWnMp4drjR4k)
> 
> 逆天 你这个是deeplx，不是deepl

原来他俩不一样 ^_^

**Comment by ZGGSONG** [comment]
请分清自建服务和DeepL官方服务
