### ISSUE TITLE
OCR 用不了

### ISSUE THREAD

**Issue by GeniusAng** [ZGGSONG/STranslate#151]
运行cleanocr.bat显示：
Deleting ocr dlls...
找不到 D:\Program Files\STranslate_1.1.6.704_win-x64\common.dll
找不到 D:\Program Files\STranslate_1.1.6.704_win-x64\concrt140.dll
找不到 D:\Program Files\STranslate_1.1.6.704_win-x64\libiomp5md.dll
找不到 D:\Program Files\STranslate_1.1.6.704_win-x64\mfc140.dll
找不到 D:\Program Files\STranslate_1.1.6.704_win-x64\mfcm140.dll
找不到 D:\Program Files\STranslate_1.1.6.704_win-x64\mkldnn.dll
找不到 D:\Program Files\STranslate_1.1.6.704_win-x64\mklml.dll
找不到 D:\Program Files\STranslate_1.1.6.704_win-x64\msvcp140.dll
找不到 D:\Program Files\STranslate_1.1.6.704_win-x64\msvcp140_1.dll
找不到 D:\Program Files\STranslate_1.1.6.704_win-x64\msvcp140_2.dll
找不到 D:\Program Files\STranslate_1.1.6.704_win-x64\msvcp140_atomic_wait.dll
找不到 D:\Program Files\STranslate_1.1.6.704_win-x64\msvcp140_codecvt_ids.dll
找不到 D:\Program Files\STranslate_1.1.6.704_win-x64\opencv_world470.dll
找不到 D:\Program Files\STranslate_1.1.6.704_win-x64\PaddleOCR.dll
找不到 D:\Program Files\STranslate_1.1.6.704_win-x64\paddle_inference.dll
找不到 D:\Program Files\STranslate_1.1.6.704_win-x64\vcamp140.dll
找不到 D:\Program Files\STranslate_1.1.6.704_win-x64\vccorlib140.dll
找不到 D:\Program Files\STranslate_1.1.6.704_win-x64\vcomp140.dll
找不到 D:\Program Files\STranslate_1.1.6.704_win-x64\vcruntime140.dll
找不到 D:\Program Files\STranslate_1.1.6.704_win-x64\vcruntime140_1.dll
系统找不到指定的文件。
ocr dlls deleted.
请按任意键继续. . .

**Comment by ZGGSONG** [comment]
#103
