### ISSUE TITLE
划词翻译复制内容

### ISSUE THREAD

**Issue by JacobLee713** [ZGGSONG/STranslate#152]
最近注意到使用划词翻译会把划词内容直接复制，导致剪贴板混乱，找了一下没有找到有关的开关，希望作者大大可以修改一下

**Comment by ZGGSONG** [comment]
原理就是使用剪贴板作为取词中转，不仅仅是本款软件，目前几乎所有滑词取词逻辑都是基于此，包括deepl官方客户端，windows没有一个可用的统一的全局获取文本的方案

**Comment by JacobLee713** [comment]
那如果可以设定一个划词后删除此次剪贴板的逻辑感觉也是个不错的方案

**Comment by ZGGSONG** [comment]
我记得我在开发的时候尝试过，然后微软自带剪贴板历史记录和第三方剪贴板历史记录ditto均不会删除该条记录。好像只影响直接粘贴。还有一个是win32 api访问剪贴板经常会出现问题😂，你会发现我有个设置叫尝试解决取词失败的选项和延长取词时间间隔的选项，还是会出现有概率取不到词🤣

**Comment by JacobLee713** [comment]
好滴，了解了，感谢作者大大耐心解答
