### ISSUE TITLE
大佬，可以添加一个回译功能不

### ISSUE THREAD

**Issue by GINA78879** [ZGGSONG/STranslate#153]
就是把翻译好的再次返回 翻译成原来的语言，查看意思是否正常；多音多意有时候容易翻译错误
比如，汉语→翻译英语→回译成汉语（查看翻译 的意思是否正确）
![image](https://github.com/user-attachments/assets/e9ae6a3b-9322-4de2-b756-d9bb5e7b16e3)

**Comment by ZGGSONG** [comment]
可以
