### ISSUE TITLE
开启调整内容后立即翻译无效

### ISSUE THREAD

**Issue by dlzmoe** [ZGGSONG/STranslate#155]
如视频所示，删除或者新增文本，没有理解翻译，点击 Enter 后才翻译，是我对这个功能的理解存在偏差吗 :)

https://github.com/user-attachments/assets/28603469-639b-442d-a382-d050858285f2

**Comment by ZGGSONG** [comment]
是的，请把鼠标移动到文字右侧小图标上，会有更详细的描述
