### ISSUE TITLE
1.1.7.808版，截图翻译有问题

### ISSUE THREAD

**Issue by uniquMonte** [ZGGSONG/STranslate#156]
快捷键使用截图翻译之后，软件主界面闪了一下，立马消失了，并没有像划词翻译一样会显示出软件的翻译结果界面

**Comment by ZGGSONG** [comment]
[test](https://github.com/ZGGSONG/STranslate/releases/download/0.01/test.zip)

你试试这个看  有没有解决这个问题

**Comment by uniquMonte** [comment]
这个test功能正常，截图翻译可以正常使用

**Comment by ZGGSONG** [comment]
嗯嗯，明天再发一个版本，原理上就是关闭截图窗口之前拿到了截图结果给到主窗口，关闭截图窗口有个短暂的焦点转移，导致主窗口失焦，就隐藏掉了。这个比较不好说，我自己电脑上基本没有出现，所以当时就没注意。

**Comment by uniquMonte** [comment]
谢谢
