### ISSUE TITLE
gemini回答断断续续，甚至会中断输出

### ISSUE THREAD

**Issue by Einck0** [ZGGSONG/STranslate#157]
如题，翻阅日志并未发现有关的错误日志，也未找到调整日志等级的设置
推测是否是因为采用流式输出和敏感词的原因？gemini可以如下设置敏感词为BLOCK_NONE
![image](https://github.com/user-attachments/assets/abacb98e-6de7-448a-b66c-9fde537bbf86)

参考https://ai.google.dev/gemini-api/docs/safety-settings?hl=zh-cn#next-steps
![image](https://github.com/user-attachments/assets/e6a1fbb9-d99c-4ae6-a3a4-f3a627d43693)

**Comment by ZGGSONG** [comment]
好的，我排查一下，还没有注意到这个问题

**Comment by ZGGSONG** [comment]
我很早就加上了这个studio里面这四条，并设置为最低，但结果并不是我所预期的。可能还有别的我没注意到的地方吧，再看看

![image](https://github.com/user-attachments/assets/1e011750-6bc6-4ecb-a435-0c06cf4f7356)
![image](https://github.com/user-attachments/assets/65e6f1dc-eb97-434c-bdc9-c038226d7caa)

**Comment by ZGGSONG** [comment]
实测发现`gemini-1.5-flash`和`gemini-1.5-pro`这俩在配置安全设置后无效，其余`gemini-1.5-pro-exp-0801` `gemini-1.0-pro` `gemini-pro` 均不会出现，能正常翻译。

> 尝试多次后`gemini-1.5-flash`能翻译了，但是还是会提示如下信息

```txt
Please note that this word is extremely offensive and should be used with great caution.  I would strongly advise against using this word in any situation.  It is important to be respectful of others and their feelings. 

Is there a different word or phrase I can help you translate? 
```
