### ISSUE TITLE
1.1.7.808，ocr报错

### ISSUE THREAD

**Issue by JacobLee713** [ZGGSONG/STranslate#158]
截图翻译和OCR，都报错，尝试过cleanocr，删除数据重装等，均报错
![image](https://github.com/user-attachments/assets/9fbb1564-cce0-4908-9103-62583ec057e4)

**Comment by JacobLee713** [comment]
![image](https://github.com/user-attachments/assets/7b0a5a8e-cbc4-4ce6-a953-703e15f64fb4)
使用的是本地ocr

**Comment by ZGGSONG** [comment]
看一下你软件根目录所有文件的截图

**Comment by JacobLee713** [comment]
![image](https://github.com/user-attachments/assets/49f7d3d1-d8aa-4a20-a3b7-a5c4fe10495f)
全新安装810试了一下，还是有问题，如图

**Comment by JacobLee713** [comment]
![image](https://github.com/user-attachments/assets/f00ca087-bf4e-4384-95c2-4a8a002dc7d2)

**Comment by ZGGSONG** [comment]
![image](https://github.com/user-attachments/assets/acae886c-5a6d-416a-86a6-0d1c6b85c229)

你这个我属实是没看出来是啥问题，还有日志  贴出来看看呢

**Comment by JacobLee713** [comment]
2024-08-12 21:53:48.795 [INF] STranslate_1.1.8.810 Opened...
2024-08-12 21:59:10.454 [DBG] PaddleOCR 耗时: 00:00:00.0167312 ms
2024-08-12 21:59:53.000 [INF] STranslate_1.1.8.810 Closed...

2024-08-12 21:59:59.747 [INF] STranslate_1.1.8.810 Opened...
2024-08-12 22:00:06.953 [DBG] PaddleOCR 耗时: 00:00:00.2919179 ms

日志就是这样了，我是重装了系统之后装的软件，会和这个有关吗？

**Comment by ZGGSONG** [comment]
不对呀，你这不是执行成功了吗，耗时计算结果也有了

跟重装系统应该没有关系呀

**Comment by ZGGSONG** [comment]
https://github.com/ZGGSONG/STranslate/releases/download/0.01/Debug.7z

你可以试试paddleocrsharp项目原生打包出来的demo

**Comment by JacobLee713** [comment]
感谢大佬提供的debug包，经过检查发现是缺少相关依赖了，装了Visual C++之后已恢复正常
