### ISSUE TITLE
截图翻译自动全屏翻译

### ISSUE THREAD

**Issue by ZHANGJUN-OK** [ZGGSONG/STranslate#16]
1、截图翻译快捷键，没有调出截图，直接就全屏翻译了，

2、关闭鼠标滑词后，置顶也取消了，我想一直置顶，

3、能不能把截图翻译，ocr这些功能放在窗口上，这样就可以直接双击启用了，

谢谢谢谢，这是我用过最好用的翻译软件了，我mac用的也是bob，但是收费，需要自己去主流翻译软件申请体验时长，后面就得充值了。

win上能有这个软件简直就是福音

**Comment by ZGGSONG** [comment]
第一个问题，不清楚问题原因，我得再排查，后面的feature都实现了，感谢建议

**Comment by ZGGSONG** [comment]
close with https://github.com/ZGGSONG/STranslate/releases/tag/1.0.5.131
