### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by xhybb** [ZGGSONG/STranslate#160]
![2024-08-11-19-12-28](https://github.com/user-attachments/assets/55d205cf-8bdc-47af-99a8-e93211da825c)
希望原文输入框和语种选项框，能增加显示／隐藏设置

**Comment by ZGGSONG** [comment]
ctrl shift a

**Comment by xhybb** [comment]
> ctrl shift a

🥶原来还有软件内快捷键，建议还是在软件内添加各个热键功能使用说明，一般人使用软件不会打开网站去看使用说明

**Comment by ZGGSONG** [comment]
> 
> 
> 
> 
> 
> 
> > ctrl shift a
> 
> 
> 
> 🥶原来还有软件内快捷键，建议还是在软件内添加各个热键功能使用说明，一般人使用软件不会打开网站去看使用说明

嗯嗯，回头在快捷键设置页面加一栏软件内热键说明
