### ISSUE TITLE
可以为gemini添加下拉复选框用于关闭安全限制

### ISSUE THREAD

**Issue by elfcute** [ZGGSONG/STranslate#162]
gemini有时候翻译一些词或句子，会拒绝回答或者断断续续。
可以提供一个选项让用户自行关闭安全限制（gemini是可以关闭安全限制的），
![image](https://github.com/user-attachments/assets/a11b9c08-5e8c-46c9-89fb-12df0844c6e4)

比如下拉复选框。

话说能不能为openai和gemini添加一个temperature用以调整ai的采样散发度（采样发散度，值越小, 生成的内容越固定。当取0时，模型生成时几乎总是会选取概率最大的Token（词元））

**Comment by ZGGSONG** [comment]
#157
