### ISSUE TITLE
替换翻译无效

### ISSUE THREAD

**Issue by deepinsc2020** [ZGGSONG/STranslate#163]
翻译服务和OCR服务都添加了， 热键设定为ALT+Q，按下后无反应，如果是页首，会往下滑动一屏，不知道什么情况

**Comment by ZGGSONG** [comment]
替换翻译需要在配置里面配置替换翻译的服务

**Comment by deepinsc2020** [comment]
配置了   内置的和小牛的我都试过  没反应

**Comment by ZGGSONG** [comment]
你看下你是不是装了什么安全软件把软件的键盘模拟屏蔽了，替换翻译原理是翻译获取结果后模拟用户键盘输出，目前已知360会干这个事

**Comment by deepinsc2020** [comment]
系统上只有火绒，退出后一样无效
而且快捷键只有替换翻译无效，其余的都正常

**Comment by deepinsc2020** [comment]
刚又看了下  是我理解错误吗？  这个不会原地替换？   我试着网页上复制了一段英文  然后切换到其他软件的输入窗口    然后按下快捷键会输入翻译结果     这个功能是就这样用的吗？   我以为是类似有道词典那样原地替换为中文

**Comment by ZGGSONG** [comment]
https://github.com/ZGGSONG/STranslate/releases/tag/1.1.5.703

请看该发布页面 gif，演示了插入文本和替换翻译

替换翻译是选中文本，热键触发，直接翻译并替换掉原始文本

**Comment by deepinsc2020** [comment]
好的  谢谢    我理解成了覆盖翻译了   请问将来有机会加入覆盖翻译吧

**Comment by ZGGSONG** [comment]
按照你的描述，你把内容复制粘贴到需要输入的地方，然后替换翻译不就行了

**Comment by deepinsc2020** [comment]
是的  我和覆盖翻译搞混了   希望将来加入原位置截图覆盖翻译：类似有道词典那种，网页上截图然后自动原位置替换为中文

**Comment by ZGGSONG** [comment]
#36
