### ISSUE TITLE
替换翻译存在意外的换行

### ISSUE THREAD

**Issue by xinhai-ai** [ZGGSONG/STranslate#164]
翻译服务：openai，模型gpt-4o-mini，promot是默认的翻译promot
使用替换翻译的时候存在不应该有的换行，这会导致消息提前发出
测试句：**在中文中的6有什么含义我在中文的社交媒体上经常见到**

另外，当其中的6转换为六时，则没有存在该问题
![PixPin_2024-08-13_17-38-36](https://github.com/user-attachments/assets/9ee84fe6-1db4-4d45-bdf6-88cd782f19ee)

**Comment by ZGGSONG** [comment]
测试了一下，应该是键盘模拟的问题。

**Comment by ZGGSONG** [comment]
47394ca49040bf41d4d44d01b0f456fdd6233317
