### ISSUE TITLE
win10下alt+tab会显示空白窗口的多任务切换，占用画面

### ISSUE THREAD

**Issue by SkulFoot** [ZGGSONG/STranslate#165]
在win10下alt+tab会显示空白窗口的多任务切换，具体如图，请问有什么办法取消吗？有一点占用画面，谢谢！
![无标题](https://github.com/user-attachments/assets/d633b4b3-b9e4-4592-b7d3-df46586d2173)

**Comment by SkulFoot** [comment]
我记得我之前在win11用您的程序，多任务切换是不显示空白窗口的。

**Comment by ZGGSONG** [comment]
这是什么条件下触发的

**Comment by SkulFoot** [comment]
> 这是什么条件下触发的

设置了以管理员权限开机自动启动，然后开机就会这样，是不是和我的系统有关呢？我用的是win10 IoT 企业版 LTSC 21H2

**Comment by SkulFoot** [comment]
> 设置里面有个失去焦点不隐藏界面那个打开/关闭保存后都试试呢，看看效果如何，如果该项关闭的话，会占用tab页的只有设置页面、OCR页面和截图界面了，如果你自始至终没有打开过这几个，配置也是关闭，那可能就是wpf框架和windows系统之间的问题了
> 
> 目前手头没有这个版本系统的机器，不好进行测试

 打开和关闭“失去焦点不隐藏界面”都会有空白窗口，我设置主界面显示关闭图标，只要关闭过一次主界面，这个问题就解决了。看来这个系统下，默认开启程序，主界面就会占用多任务切换的窗口。

**Comment by ZGGSONG** [comment]
> 另外，如果是直接在alt+tab下关闭这个空白窗口，整个程序都会被关闭，这个关闭权限最高。单独只关闭主界面，不影响任何使用，并且空白窗口也会消失。

感觉这是个底层的bug。如果只是主窗口没有在多任务页面隐藏的话关闭也不应该退出程序的。

**Comment by zzm-note** [comment]
> 这是什么条件下触发的

win11 23H2下测试，开启了“启动时隐藏主界面”，启动后就会出现alt+tab下的空白窗口，跟管理员权限启动这个无关。任务管理器中查看，stranslate这个应用目前是前台应用。
当然手动打开一下主界面或使用一下翻译后续就不会出现多任务的空白窗口了，但是开机后一起没用到stranslate的情况下，强迫症就有点接受不了了:)。

所以“启动时隐藏主界面”这个功能可能需要优化一下？不排除是底层有bug。

**Comment by zzm-note** [comment]
> 这是什么条件下触发的

win11 23H2下测试，开启了“启动时隐藏主界面”，启动后就会出现alt+tab下的空白窗口，跟管理员权限启动这个无关。任务管理器中查看，stranslate这个应用目前是前台应用。
当然手动打开一下主界面或使用一下翻译后续就不会出现多任务的空白窗口了，但是开机后一起没用到stranslate的情况下，强迫症就有点接受不了了:)。

所以“启动时隐藏主界面”这个功能可能需要优化一下？不排除是底层有bug。
