### ISSUE TITLE
便携版与数据包存储位置

### ISSUE THREAD

**Issue by wordpure** [ZGGSONG/STranslate#167]
1. 能否添加一个便携版，将配置保存到应用目录，以方便在 U 盘中使用
2. Paddle OCR 数据包这种第三方依赖，单独建一个文件夹存放会不会比较好？
	目前是全部放应用根目录，看起来有点混乱。

![图片](https://github.com/user-attachments/assets/f114f586-b23e-468d-8ee3-2b4c80791493)

**Comment by ZGGSONG** [comment]
1. 你对便携版的理解应该是有点问题，免安装即为便携版，你应该想说的是可选配置路径，这个我当初考虑过，比较容易出问题，就没开发。你要是真想应对这样的需求，完全可以备份一个配置放你U盘，新电脑上直接导入即可。
2. Paddleocr是使用的第三方的一个库PaddleOCRSharp，引入后默认就是在根目录，如果不启用则不加载那些依赖的动态链接库。有想过把所有动态链接库整理放到一个目录下，最外层只留一个exe，但是不太清楚这方面好不好实现，我去学习学习看看。有结果的话就给优化一下

**Comment by wordpure** [comment]
感谢大佬🌹

便携版在国内有好几种说法，不过我指的其实是国外的 [Portable Application](https://en.wikipedia.org/wiki/Portable_application)，即不写注册表，所有数据和设置都存储在应用目录的程序。

![image](https://github.com/user-attachments/assets/a765f784-b0eb-42e8-87e7-913fff6dbd3d)

> 可选配置路径，这个我当初考虑过，比较容易出问题，就没开发

参考 mpv 的做法，在应用目录含有指定文件夹时，优先使用该文件夹的配置，没有的话再使用 appdata 的配置。这种会不会比较可行？

![image](https://github.com/user-attachments/assets/3d8b4457-b00c-4a68-8b36-9b7a63aeeca5)

**Comment by ZGGSONG** [comment]
有点糊涂了我，这个方案可行度高，回头给你加上。

感谢提供思路🌹

**Comment by ZGGSONG** [comment]
1. 分离可执行程序和动态链接库这个有方案，但是目前不太想做，投入产出比太小，等后面有这个想法了在做 [https://github.com/velopack/velopack](https://github.com/velopack/velopack)
2. 便携配置只需要在根目录添加 `portable_config` 即可启用，仅在`portable_config`中查找配置，移除后仅在`appdata/local`中找，该方案与本软件结合最为方便

**Comment by wordpure** [comment]
期待❤️
