### ISSUE TITLE
建议增加原文与译文对照模式、术语库

### ISSUE THREAD

**Issue by simonecho** [ZGGSONG/STranslate#168]
Description
作为一个翻译工具，最基础的就是要能够原文与译文对照，比如谷歌、deepl的界面都是极好的案例。
STranslate如果要想走得更远，至少要符合译者的习惯。
当文本较长时，上下对照难以实时调整译文。
具体可参考
[https://translate.google.com/](https://translate.google.com/)
[https://www.deepl.com/](https://www.deepl.com/)
译者的另一个刚需是术语库，在特定领域一些固定表达有其特殊含义，然而翻译引擎无法识别具体领域，能够引入术语库的话可以很好地规避这个问题。

Application Scenario
建议增设布局选项
建议考虑术语库功能。
References
No response

**Comment by ZGGSONG** [comment]
欢迎pr🙂
