### ISSUE TITLE
爱词霸服务不可用

### ISSUE THREAD

**Issue by Olimiya** [ZGGSONG/STranslate#17]
添加爱词霸服务，然后使用时不可用。

![image](https://github.com/ZGGSONG/STranslate/assets/35156329/6a988932-c359-4822-a6e6-e7e658f03c8b)

![image](https://github.com/ZGGSONG/STranslate/assets/35156329/2ba523fc-ad8f-4333-a780-e158e9646473)

**Comment by ZGGSONG** [comment]
是的，这就是为什么我默认关闭了，他们最近更新了通讯内容，都加密了，我暂时还没搞定🤣，所以这个api暂时用不了，回头搞定了我再更新这个api代码

**Comment by Olimiya** [comment]
哈哈是这样，那辛苦作者大大了～

**Comment by ZGGSONG** [comment]
[1.0.6.201版本以后支持本地服务](https://github.com/ZGGSONG/STranslate#%E6%9C%8D%E5%8A%A1)，每个人使用自己的独立IP，基本避免了服务不可用。
