### ISSUE TITLE
为什么识别不到OCR文件

### ISSUE THREAD

**Issue by CNEA-lw** [ZGGSONG/STranslate#170]

**Comment by CNEA-lw** [comment]
OCR出错: Unable to load DLL 'PaddleOCR.dll' or one of its dependencies: 找不到指定的模块。 (0x8007007E)

**Comment by ZGGSONG** [comment]
#158

**Comment by CNEA-lw** [comment]
> #158

感谢查看，问题已经好了，和他有些相似但是装v c++之前重启两三次用管理员身份在运行成功的。
