### ISSUE TITLE
WebDAV 配置失败

### ISSUE THREAD

**Issue by wordpure** [ZGGSONG/STranslate#171]
使用 [AList](https://alist.nn.ci/zh/guide/webdav.html) 的 WebDAV，提示【请检查配置是否正确】。

![图片](https://github.com/user-attachments/assets/c526962b-655d-4911-8e3f-db1eeaf493dc)

换成 [infiniCloud](https://infini-cloud.net/en/modules/mypage/usage/)，提示【导出失败】。

![图片](https://github.com/user-attachments/assets/279867ff-7efe-4872-8c70-ed32edc35896)

同样的 WebDAV 配置，在暴力猴、Stylus 这些都能正常同步，所以应该不是服务器配置问题。

**Comment by ZGGSONG** [comment]
我明天测试一下

**Comment by wordpure** [comment]
顺带一提，帮助手册里时长超过 5 秒的 GIF ，建议都拆成几个小片段，或者直接转成视频。

像 [STranslate | 导入导出](https://stranslate.zggsong.com/docs/config/backup) 这一页的 GIF，播完要二三十秒，没法暂停，想回看还要等它再播一遍，挺难受的😂

**Comment by ZGGSONG** [comment]
1. alist 似乎本身就存在一些问题，[alist文档](https://alist.nn.ci/zh/guide/webdav.html)下留言和[issue](https://github.com/alist-org/alist/issues/6846)。我当时开发使用群晖webdav测试的没有问题，又测试了坚果云也是可以的。而alist在一些第三方webdav客户端上无法连接：WinSCP(连的上alist无法加载上传)、AirLiveDrive(无法添加alist webdav)，群晖webdav、坚果云均可！
2. 这个我暂时无法注册，后续再试试

**Comment by wordpure** [comment]
怪了，我用坚果云也是提示导出失败

![image](https://github.com/user-attachments/assets/ec9dfd9b-1696-4eac-882d-35e5d6c4dd8a)

**Comment by ZGGSONG** [comment]
坚果云密码不是登陆密码，是自己创建的应用密码，是不是这个给错了

**Comment by wordpure** [comment]
> 坚果云密码不是登陆密码，是自己创建的应用密码，是不是这个给错了

用的是应用密码没错

**Comment by ZGGSONG** [comment]
emmm，我用1.1.9.821测试坚果云结果如下


![image](https://github.com/user-attachments/assets/294f648a-3034-45fe-8a00-e095983263a8)

![image](https://github.com/user-attachments/assets/a3d4c315-4dbe-4c45-899a-b60ef0429ccb)

**Comment by ZGGSONG** [comment]
> 试过管理员与非管理员、便携模式与非便携模式运行，应用目录下可以看到时间日期文件夹被创建，但都提示导出失败

跟这些没关系

**Comment by JunoChina** [comment]
> > emmm，我用1.1.9.821测试坚果云结果如下
> 
> 那就不清楚了😂

我也是配置了导出一直失败 先用一次本地的导出功能 然后切换回去就能导出成功了

**Comment by wordpure** [comment]
> 我也是配置了导出一直失败 先用一次本地的导出功能 然后切换回去就能导出成功了

感谢分享，不过试了下这个方法在我这边无效😂

**Comment by JunoChina** [comment]
> ![image](https://private-user-images.githubusercontent.com/49741009/361758375-11a6ab43-2d6f-49fb-a803-ed1775341641.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4OTgxNzIsIm5iZiI6MTcyNDg5Nzg3MiwicGF0aCI6Ii80OTc0MTAwOS8zNjE3NTgzNzUtMTFhNmFiNDMtMmQ2Zi00OWZiLWE4MDMtZWQxNzc1MzQxNjQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDAyMTc1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2NTdiMzYxZjcxYjg4ZjQ1ZjFlMWVhZmYyOTg2ZDhlNjdiY2I2NDMwMjFhNzk0ZWVkZWFhNzE3N2NlNDRjMGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2HTH89WaaBJ9MIKKhyDvDZxZUVJvfvdQCh5JAG0Cnk8)
> 
> 你们进群 有空一起调试一下 看是什么问题

经过我测试 我在坚果云把同步文件夹stranslate删除之后就会再次导出失败 自己手动创建一个stranslate文件夹之后 就能导出成功了

**Comment by ZGGSONG** [comment]
原来是导出的时候忘了检查有无目录了！已修复
