### ISSUE TITLE
无法使用日语或韩语等其他语音的发言

### ISSUE THREAD

**Issue by elfcute** [ZGGSONG/STranslate#176]
![image](https://github.com/user-attachments/assets/2f3f9a60-a054-4f1f-acb5-8c776faf83bc)
![image](https://github.com/user-attachments/assets/49d002bd-4f33-4ed0-bd50-95e3b7bd5420)
目前只能使用中英发音，其他语言点击发音没有声音，我是还要下载什么依赖语音包吗？

**Comment by ZGGSONG** [comment]
你使用的是什么TTS服务

**Comment by elfcute** [comment]
> 你使用的是什么TTS服务

内置的

**Comment by ZGGSONG** [comment]
![image](https://github.com/user-attachments/assets/73b072a1-6bb8-481b-bf72-85c438a70b3d)

System.Speech.SpeechSynthesizer在中文windows系统上只支持这两个语种

**Comment by elfcute** [comment]
> ![image](https://private-user-images.githubusercontent.com/49741009/362312870-73b072a1-6bb8-481b-bf72-85c438a70b3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4NTQ0MzgsIm5iZiI6MTcyNDg1NDEzOCwicGF0aCI6Ii80OTc0MTAwOS8zNjIzMTI4NzAtNzNiMDcyYTEtNmJiOC00ODFiLWJmNzItODVjNDM4YTcwYjNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDE0MDg1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5OGFlNTFhNDMxNjQ0ZTRkNTczMzBlYmQxNjg4MmJhZGI1YWUxOWU1MjE0ODNjM2I4MGU1NmU5YWVkYTYxOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wsC93xgp9UK1xOdM1yd5mPY9uvxyMYrWXo4V-8-BD88)
> 
> System.Speech.SpeechSynthesizer在中文windows系统上只支持这两个语种

好吧 这一点太伤了
STranslate能内置‘Lingva’吗，我看pot的语音内置的这个，然后可以支持其他发音
![image](https://github.com/user-attachments/assets/2f82d4a8-cadc-45a3-ac14-ee625f063936)

**Comment by ZGGSONG** [comment]
目前不支持

**Comment by ZGGSONG** [comment]
最新版已经接入lingva，并且azure tts也可以支持多语言。
