### ISSUE TITLE
大佬新增的lingya语音为啥使用不了？

### ISSUE THREAD

**Issue by Resourcelover** [ZGGSONG/STranslate#178]
![image](https://github.com/user-attachments/assets/23d0431c-cef8-4a0b-8b9e-feb2cf0f5f80)
![image](https://github.com/user-attachments/assets/ee02fac6-1fce-4c61-8532-a5e5fb7734ce)
我看了pot的，但是它也没有配置，默认是内置在软件里面了。

**Comment by ZGGSONG** [comment]
从截图看你好像没有启用lingva tys服务

**Comment by ZGGSONG** [comment]
> 我看了pot的，但是它也没有配置，默认是内置在软件里面了。

lingva是个自建服务，你可以使用lingva readme中公开的几个服务地址，pot是默认为空自己给了一个，我没钱买服务器，没有自建而已。

**Comment by Resourcelover** [comment]
> > 我看了pot的，但是它也没有配置，默认是内置在软件里面了。
> 
> lingva是个自建服务，你可以使用lingva readme中公开的几个服务地址，pot是默认为空自己给了一个，我没钱买服务器，没有自建而已。

好吧 我使用它公开的几个服务地址 也还是没有声音
![image](https://github.com/user-attachments/assets/b515caba-4707-44bf-ae7a-acff78a360d5)
![image](https://github.com/user-attachments/assets/cd629e58-cad8-437c-babb-342711f96b8d)

**Comment by ZGGSONG** [comment]
日志提供一下呢

**Comment by ZGGSONG** [comment]
我用https://lingva.thedaviddelta.com/测试了一下没有问题，lingva需要传入语种类型，所以依赖设置里的语种识别，如果语种识别错误也会导致无法正常文本转语音

**Comment by Resourcelover** [comment]
大佬我才看到信息，不好意思，我现在找到原因了。
我先前的语种识别选择的是谷歌识别，播放不了声音
然后我现在改成了百度识别就可以使用了

**Comment by ZGGSONG** [comment]
搭建Lingva服务：
https://lingva.zggsong.com

后续版本软件内默认使用该服务
