### ISSUE TITLE
复制按钮位置控制功能

### ISSUE THREAD

**Issue by ApliNi** [ZGGSONG/STranslate#18]
![{A5649283-E7CB-4c20-988D-59D2E84D93C3}](https://github.com/ZGGSONG/STranslate/assets/59365724/4993a114-2d99-42e3-b682-fc6a985c7675)

将底部的复制按钮移动到上面似乎更方便使用 (特别是对于翻译长文本), 以及可以做到不展开就能复制. 请问能否考虑添加一个选项来控制按钮位置? 

以及有一个 bug? 翻译长文本时, 第一次翻译或者点击其他窗口后再点击界面边框部分都会自动滚动到中间 (开启置顶).

**Comment by ZGGSONG** [comment]
close with https://github.com/ZGGSONG/STranslate/releases/tag/1.0.5.131
