### ISSUE TITLE
显示页面更精简

### ISSUE THREAD

**Issue by kscale** [ZGGSONG/STranslate#182]
通过划词翻译或复制文本到剪贴板，然后STranslate 直接给出翻译内容，不要显示输入的内容，如图红框所示。

我已经看过文档并试过快捷键，目前没找到不显示输入框，只显示翻译的区域的方法，不知道是否能支持。同类我用过[Tran](https://github.com/Borber/Tran),[translator](https://github.com/zu1k/translator)

![图片](https://github.com/user-attachments/assets/4543ef46-e1a6-410d-9d18-58bdb373068e)

**Comment by ZGGSONG** [comment]
1. 偏好设置-热键设置-软件热键: `Ctrl`+`Shift`+`A`

2. [文档软件内快捷键](https://stranslate.zggsong.com/docs/#%E8%BD%AF%E4%BB%B6%E5%86%85%E5%BF%AB%E6%8D%B7%E9%94%AE)
