### ISSUE TITLE
建议增加快捷键，支持复制翻译内容

### ISSUE THREAD

**Issue by Postrantor** [ZGGSONG/STranslate#22]
翻译界面可以通过快捷键唤醒；
通过enter可以快速翻译；

希望可以添加快捷键，可以对翻译的内容进行复制，如果是多个翻译结果以 <快捷键>+<num1> 的方式扩展？
或者对多个翻译结果分别支持快捷键复制？

希望作者能考虑添加该功能，这样可以做到少动用鼠标的效果，感谢！

**Comment by ZGGSONG** [comment]
closed in [https://github.com/ZGGSONG/STranslate/releases/tag/1.0.7.304](https://github.com/ZGGSONG/STranslate/releases/tag/1.0.7.304)

**Comment by Postrantor** [comment]
感谢作者支持
