### ISSUE TITLE
能否设置简洁模式

### ISSUE THREAD

**Issue by XbuLee** [ZGGSONG/STranslate#25]
![Clip_2024-02-21_15-30-46](https://github.com/ZGGSONG/STranslate/assets/20644303/da3f13d9-5885-4a81-ba48-ce861cf3ad03)
在连续阅读情况下，我只关注图中红框部分内容，能否折叠上部分内容，或者单独设置一个简洁模式。

**Comment by ZGGSONG** [comment]
如果配置了多个服务，多个输出呢，多个结果，隐藏其他仅显示（包括输入框）某个指定输出结果，是这个意思么。感觉我还是没太理解你的意思

**Comment by XbuLee** [comment]
![Clip_2024-02-23_14-00-28](https://github.com/ZGGSONG/STranslate/assets/20644303/a88a3e79-3cf5-4365-a99b-a26206d98354)
在日常使用中，我往往只关心红色框中的内容，绿色框中的内容我是不关心的，因为我很容易在页面上找到原句或者原单词。

**Comment by ZGGSONG** [comment]
了解，那可以给个软件快捷键来隐藏/显示输入部分，另外，建议添加本地服务(STranslate，1.0.6.201及更高版本)，翻译结果比谷歌精准

**Comment by XbuLee** [comment]
> 建议添加本地服务(STranslate，1.0.6.201及更高版本)，翻译结果比谷歌精准

好的，我试试。

**Comment by ZGGSONG** [comment]
closed in [https://github.com/ZGGSONG/STranslate/releases/tag/1.0.7.304](https://github.com/ZGGSONG/STranslate/releases/tag/1.0.7.304)
