### ISSUE TITLE
[Feature request]: 输入翻译窗口的输入框希望能调节大小，能够更适应不同用户的应用场景

### ISSUE THREAD

**Issue by vimbackground** [ZGGSONG/STranslate#268]
### 相关问题

有些时候复制粘贴的内容比较多，翻译时希望能看到更多的原文，目前的输入窗口无法调整高度

### 描述你希望的解决方案

希望能在前台（或后台）设置输入翻译窗口的输入框大小，并保持为默认大小

### 我确认已查询历史issues

- [X] 是

**Comment by ZGGSONG** [comment]
(e52930fd497870d24bf4990c5f7f891e09365cc8)
