### ISSUE TITLE
[Feature request]: 

### ISSUE THREAD

**Issue by sy007007** [ZGGSONG/STranslate#269]
### 相关问题

输入英文后翻译出现Invalid Request，请回复~~~

### 描述你希望的解决方案

输入英文后翻译出现Invalid Request，请回复~~~

### 我确认已查询历史issues

- [X] 是

**Comment by ZGGSONG** [comment]
服务的设置里换个模式，请求被限制了，服务端那边有限制白嫖不稳定，最稳定的还是自己申请
申请个国内服务的api，不花钱
