### ISSUE TITLE
[bug?]这个ⓘ是装饰吗？

### ISSUE THREAD

**Issue by lueluelue2006** [ZGGSONG/STranslate#27]
![image](https://github.com/ZGGSONG/STranslate/assets/153379751/58dbc8b4-37e8-4f88-8ada-b5cc9a4be3c7)
这种ⓘ按钮是装饰吗？点了好像没反应，鼠标悬停也没

**Comment by ZGGSONG** [comment]
tooltip，提示信息，鼠标放置在上面几秒钟不动就会有信息提示

**Comment by ZGGSONG** [comment]
![image](https://github.com/ZGGSONG/STranslate/assets/49741009/e4b8bdd3-7542-4cb5-94a5-621554683f37)
