### ISSUE TITLE
[Feature request]: 希望能像Deepl这样增加Ctrl+C+C的快捷键

### ISSUE THREAD

**Issue by Arcticn** [ZGGSONG/STranslate#273]
### 相关问题

作者您好，这个软件很好用，但是可惜快捷键较单调，容易产生冲突

### 描述你希望的解决方案

希望能像Deepl这样增加Ctrl+C+C的快捷键，使用体验很好，而且不容易发生冲突
![QQ_1733136887813](https://github.com/user-attachments/assets/d7302d32-2b32-47f5-b8db-a92cdfd5a713)

### 描述你所考虑的替代方案

pot-desktop和这个我感觉都不错，而且想到直接调用微信的ocr真是太聪明了。就是快捷键有点匮乏，如果您有意愿的话，还可以参考quicker这样，做一些跟鼠标交互的快捷键
![QQ_1733137345648](https://github.com/user-attachments/assets/7767c29f-21ad-43cf-b3da-16fb5eed89d0)

### 我确认已查询历史issues

- [X] 是

**Comment by ZGGSONG** [comment]
不好意思，一直忘了回，快捷键这块目前不太想动。
