### ISSUE TITLE
[Feature request]: 能否给日文韩文的ocr识别增加一个快捷键

### ISSUE THREAD

**Issue by bohailaoyao** [ZGGSONG/STranslate#278]
### 相关问题

PaddleOCR经常会把日文当成中文来识别

### 描述你希望的解决方案

所以觉得如果能给指定语言ocr设置快捷键可能会比较方便

### 我确认已查询历史issues

- [X] 是

**Comment by ZGGSONG** [comment]
没有计划,可fork后自行开发
