### ISSUE TITLE
[Bug]: 本地翻译（ST）总会报奇奇怪怪的bug，谷歌翻译倒是正常的

### ISSUE THREAD

**Issue by nininiman** [ZGGSONG/STranslate#279]
### 预期情况

本地翻译正常反馈结果

### 实际情况

![屏幕截图 2024-12-10 224851](https://github.com/user-attachments/assets/b4184d78-4ded-4b8c-b060-c076f3301bf4)
![屏幕截图 2024-12-10 224916](https://github.com/user-attachments/assets/fa65e11e-177b-4e51-b3ec-95839c1d05f9)
![屏幕截图 2024-12-10 225015](https://github.com/user-attachments/assets/07446582-166b-42cd-9e73-872ee5001e11)

### 复现方法

不确定？偶发的，偶尔会出现，偶尔不会，换网/重新下载覆盖，都没用

### 日志信息

[log20241112.log](https://github.com/user-attachments/files/18081413/log20241112.log)
[log20241115.log](https://github.com/user-attachments/files/18081417/log20241115.log)
[log20241116.log](https://github.com/user-attachments/files/18081418/log20241116.log)
[log20241120.log](https://github.com/user-attachments/files/18081419/log20241120.log)
[log20241210.log](https://github.com/user-attachments/files/18081421/log20241210.log)
[log20241210_001.log](https://github.com/user-attachments/files/18081422/log20241210_001.log)

### 额外信息

前三个版本也会出现，当时是重新覆盖安装能解决本地翻译不可用的问题，现在覆盖安装也不行QAQ

### 我确认已更新至最新版本

- [X] 是

### 我确认已查询历史issues

- [X] 是

**Comment by ZGGSONG** [comment]
![图片](https://github.com/user-attachments/assets/4611b665-19fb-4f02-9473-f1a48185bdf4)

试试模式二呢

**Comment by nininiman** [comment]
[模式二也会报错QAQ，模式一/二的联通测试都是失败，换了网络也没有改善
[log20241211.log](https://github.com/user-attachments/files/18089679/log20241211.log)
![屏幕截图 2024-12-11 124533](https://github.com/user-attachments/assets/44fd2624-b663-4bad-8ad9-01bad5c0231c)

**Comment by ZGGSONG** [comment]
服务端限制了，没办法，你可以尝试别人写的deepl服务

**建议还是申请api最稳定，大都免费**
