### ISSUE TITLE
[Feature request]: 增强外接显示器时在非主窗口中唤出并显示窗口支持。

### ISSUE THREAD

**Issue by Andy365-365** [ZGGSONG/STranslate#280]
### 相关问题

当我在外接显示器时在非主窗口中操作，通过快捷键唤出查词窗口，窗口并不能显示出来，已经试过窗口位置设置的开关。

### 描述你希望的解决方案

希望能在外接显示器时在非主窗口上通过快捷键唤出查词窗口。

### 我确认已查询历史issues

- [X] 是

**Comment by ZGGSONG** [comment]
> 已经试过窗口位置设置的开关

不明确你说的是哪个开关, 请提供更加详细的信息以方便解决, 请提供版本、日志、截图等信息

**Comment by ZGGSONG** [comment]
太久没有反馈  就先关闭issue了
