### ISSUE TITLE
[Feature request]: 截图翻译能否保持ocr识别结构

### ISSUE THREAD

**Issue by xelc** [ZGGSONG/STranslate#286]
### 相关问题

识别后总是连成一排，不够直观，编辑麻烦。

### 描述你希望的解决方案

保持结构，文字是几行的，识别出来就是几行的。

### 我确认已查询历史issues

- [X] 是

**Comment by ZGGSONG** [comment]
设置里自动净化关掉

**Comment by xelc** [comment]
谢谢，确实可以了。
