### ISSUE TITLE
[Feature request]: 能否添加右键菜单，谢谢

### ISSUE THREAD

**Issue by txbspgy** [ZGGSONG/STranslate#288]
### 相关问题

 能否添加右键菜单

### 描述你希望的解决方案

 能否添加右键菜单

### 我确认已查询历史issues

- [X] 是

**Comment by ZGGSONG** [comment]
有外部调用，可以配合网上一些开源的右键管理工具去实现

https://stranslate.zggsong.com/docs/invoke.html

**Comment by ZGGSONG** [comment]
软件自身并不打算计划添加该功能
