### ISSUE TITLE
[Bug]: 静默OCR后win10光标分辨率错误

### ISSUE THREAD

**Issue by Azona77** [ZGGSONG/STranslate#290]
### 预期情况

光标正常

### 实际情况

当修改Windows的"更改指针大小"选项为非 1 的值，并运行Stranslate的静默OCR后，Windows的鼠标指针变模糊，无法分辨指针形状（尺寸不变）

### 复现方法

Windows设置 - 轻松使用 - 鼠标指针 - 更改指针大小 - 设置为任意非 1 的值

管理员或非管理员启动STranslate - 进行静默OCR操作

### 日志信息

[log20241229.log](https://github.com/user-attachments/files/18269093/log20241229.log)

### 额外信息

问题原因：
- 推测是静默OCR框选后，指针出现加载符号，识别完成后，指针回复正常过程中出现参数错误或缺漏，导致系统指针分辨率出现问题。

后续操作：
- 如果不退出软件，并重新设置Windows的"更改指针大小"选项 → 指针恢复正常，但后续静默OCR后再次触发模糊问题
- 如果退出软件STranslate → 指针被重置为"更改指针大小"值为1时的尺寸，不产生模糊

### 我确认已更新至最新版本

- [X] 是

### 我确认已查询历史issues

- [X] 是

**Comment by ZGGSONG** [comment]
已修复 (2ee27538fa06f20dfaed9ee152742af09dc1c1c5)
