### ISSUE TITLE
怎么发布能够在Releases里面下的压缩包一样

### ISSUE THREAD

**Issue by Liumou123** [ZGGSONG/STranslate#3]
我修改自定义接口后发布了不是dll程序，您是怎么发布的呀，我没接触过wpf

**Comment by ZGGSONG** [comment]
没太明白你的意思，我简单介绍一下我的升级思路：
1. 本地将updater生成的程序放到主程序目录中
2. 点击升级时开启新进程打开updater.exe，并传入当前软件版本，检查本地版本与在github上打包发布的release版本是否一致，使用的github的接口
3. 点击升级后下载文件，下载完成后关闭程序并解压文件覆盖旧文件就完成了版本升级

注：此方法是在 [https://github.com/Planshit/Tai](https://github.com/Planshit/Tai) 项目中看到的，就在此项目中用上了 另外如果有自己的ftp服务器，也可以试试微软自带的 clickonce 的发布方式

**Comment by Liumou123** [comment]
不好意思,才看到,因为我修改了代码,想自定义翻译接口,
1.我发布了之后程序集不是dll,而是Newtonsoft.Json.dll.deploy,
2.我只需要本地的程序,我需要怎么发布项目呢,而且目录程序不像我下载你那个一样
