### ISSUE TITLE
主题切换无效

### ISSUE THREAD

**Issue by MangMax** [ZGGSONG/STranslate#30]
![PixPin_2024-03-05_10-57-25](https://github.com/ZGGSONG/STranslate/assets/68525017/a3a0e8e3-e76d-4e4e-8ab0-90fe0b101fb3)

**Comment by ZGGSONG** [comment]
新版本开的切换主题新增监听系统主题颜色，无法立即生效，点击保存后生效。

设置中立即生效的设置项都在后面有标注[立即生效]
