### ISSUE TITLE
进行翻译后，可以选择是否自动复制翻译结果

### ISSUE THREAD

**Issue by qixing-jk** [ZGGSONG/STranslate#31]
翻译后的结果有时需要直接使用，剪贴板也不差这一点，所以希望可以直接按一定的规则（如选择翻译排序的第一个的默认翻译结果），复制一个翻译后的结果到剪贴板

**Comment by ZGGSONG** [comment]
close with [1.0.8.313](https://github.com/ZGGSONG/STranslate/releases/tag/1.0.8.313)
