### ISSUE TITLE
启用窗口跟随鼠标后，窗口无法完全展示

### ISSUE THREAD

**Issue by qixing-jk** [ZGGSONG/STranslate#32]
1. 所遇问题
因为有时候鼠标本身在屏幕下方，又有翻译结果展开，整个窗口很大，超出屏幕所示范围
2. 解决方案
翻译后的结果窗口
- 添加滚动条
- 在窗口超出屏幕边缘时，二次调整窗口位置，使其不超出屏幕显示范围

**Comment by ZGGSONG** [comment]
窗口跟随鼠标这个功能确实有bug，一直懒得优化😂，既然提出来了 我优化优化

**Comment by ZGGSONG** [comment]
close with [1.0.8.313](https://github.com/ZGGSONG/STranslate/releases/tag/1.0.8.313)
