### ISSUE TITLE
截图时没有明显的边框和调整截图的控件

### ISSUE THREAD

**Issue by jsonvot** [ZGGSONG/STranslate#33]
截图时没有明显的边框和调整截图的控件，如果能有相应的配置，在使用时会更加明显一点

**Comment by ZGGSONG** [comment]
后续我在有空的时候再考虑优化这部分功能吧

**Comment by wxyShine** [comment]
建议增加只截图功能，，，这样就可以卸载其他截图软件了

**Comment by ZGGSONG** [comment]
> 建议增加只截图功能，，，这样就可以卸载其他截图软件了

这部分就不去和截图软件竞争了，自知本软件的截图功能才刚到能用的地步
