### ISSUE TITLE
怎么设置用快捷键翻译剪贴板呢？

### ISSUE THREAD

**Issue by wuxyhc** [ZGGSONG/STranslate#34]
怎么设置用快捷键翻译剪贴板呢？

**Comment by ZGGSONG** [comment]
![copy](https://github.com/ZGGSONG/STranslate/assets/49741009/9243a0ae-7b94-470f-8dc7-f6ce8d826ba1)

**Comment by ZGGSONG** [comment]
1. 打开监听剪贴板，确认功能开启后复制内容即可立即翻译复制内容
2. 打开界面，Ctrl + V +回车
