### ISSUE TITLE
使用deepl翻译时出现Too many requests~~~

### ISSUE THREAD

**Issue by sy007007** [ZGGSONG/STranslate#35]
使用deepl翻译时出现Too many requests，如何解决，请回复~~~
![Uploading 屏幕截图 2024-03-17 185941.png…]()

**Comment by sy007007** [comment]
![屏幕截图 2024-03-17 185941](https://github.com/ZGGSONG/STranslate/assets/97101380/88bb9055-2b93-417e-bb9c-00ed618863c5)

**Comment by ZGGSONG** [comment]
[README 疑问第二条](https://github.com/ZGGSONG/STranslate#%E7%96%91%E9%97%AE)

**Comment by sy007007** [comment]
不行，翻译很多单词时还是会出现Too many requests，请回复~~~

**Comment by sy007007** [comment]
在使用[deepl-x86_64-pc-windows-gnu-0.1.2.1.zip](https://github.com/ZGGSONG/STranslate/releases/download/0.01/deepl-x86_64-pc-windows-gnu-0.1.2.1.zip)后翻译整段句子还是会出现Too many requests，请回复~~~

**Comment by ZGGSONG** [comment]
> 在使用[deepl-x86_64-pc-windows-gnu-0.1.2.1.zip](https://github.com/ZGGSONG/STranslate/releases/download/0.01/deepl-x86_64-pc-windows-gnu-0.1.2.1.zip)后翻译整段句子还是会出现Too many requests，请回复~~~

你直接使用stranslate就行了，一样的东西，等于是集成了

**Comment by sy007007** [comment]
[deepl_api_win_x86_64.exe](https://github.com/ZGGSONG/STranslate/releases/download/0.01/deepl_api_win_x86_64.exe)在使用这个执行文件的时候出现这种情况
![屏幕截图 2024-03-18 152955](https://github.com/ZGGSONG/STranslate/assets/97101380/dca1be4d-7eed-4c72-8256-32c2a19fe7a1)
这种情况怎么解决

**Comment by ZGGSONG** [comment]
> [deepl_api_win_x86_64.exe](https://github.com/ZGGSONG/STranslate/releases/download/0.01/deepl_api_win_x86_64.exe)在使用这个执行文件的时候出现这种情况
> 
> ![屏幕截图 2024-03-18 152955](https://github.com/ZGGSONG/STranslate/assets/97101380/dca1be4d-7eed-4c72-8256-32c2a19fe7a1)
> 
> 这种情况怎么解决

这已经正常启动了，你添加一个自建服务，api填`http://127.0.0.1:8000/translate`就行了

> 这些都不用配stranslate这个服务就等价于这些，默认里面就google是逆向的google官方服务

**Comment by sy007007** [comment]
哎~还是没看懂~~~~

**Comment by sy007007** [comment]
请问如何添加一个自建服务，请回复~~~

**Comment by ZGGSONG** [comment]
![image](https://github.com/ZGGSONG/STranslate/assets/49741009/943cc1e1-0aba-4481-8c5c-6c0d0a9284df)

![image](https://github.com/ZGGSONG/STranslate/assets/49741009/2e028133-bb4e-4d6d-8c0c-2c8e40453af9)

**Comment by ZGGSONG** [comment]
新文档正在编写中，近期上线，配置基本全部gif，敬请期待...

**Comment by sy007007** [comment]
![屏幕截图 2024-03-18 182052](https://github.com/ZGGSONG/STranslate/assets/97101380/b419adea-c50a-4d38-91e1-db821c29c015)
没用啊~~~

**Comment by ZGGSONG** [comment]
大概率是你的8000端口被别的软件占用了，真实的服务并没有开起来。你别纠结了，最上面这个STranslate就是DeepL
<img width="612" alt="image" src="https://github.com/ZGGSONG/STranslate/assets/49741009/bf551d11-3b1e-42bb-b840-4806036a9e3e">

**Comment by sy007007** [comment]
原来是这样，亲你一个么么哒~~~😘😘😘

**Comment by yangchguang** [comment]
你留下来的是zu1k大佬的源码吗？

**Comment by ZGGSONG** [comment]
自己写的，现在官方一方面更严格，另一方面开始改接口了

**Comment by yangchguang** [comment]
zu1k大佬留下来的解密规则好像官方做了新的增加，现在单纯该改时间戳和根据id改空格应该是不能用了，大佬的那个镜像在多次调用之后就会导致报500的错，感觉应该也是429的问题，想看源码但是一直找不到，大佬你是自己解决这个问题了吗

**Comment by ZGGSONG** [comment]
我模拟ios客户端和浏览器的两种方式作为默认免费服务之一，但是也经常能遇到出错的情况。我没有做更深入的研究，可以去看看deeplx这个项目

**Comment by yangchguang** [comment]
哦哦，那大佬这个方法比较靠谱，只是会慢一点，deeplx这个项目的源码我已经看过了，他们没做字段超过一次LMT_handle_jobs请求的考虑，一次能翻译的内容其实很少，而且几乎也只是复刻了zu1k大佬的解密方法，现在还是会触发429的问题
