### ISSUE TITLE
STranslate 自带默认的翻译接口是什么？

### ISSUE THREAD

**Issue by yeyemp3** [ZGGSONG/STranslate#37]
翻译用的第一个STranslate翻译引擎的是什么接口？
![image](https://github.com/ZGGSONG/STranslate/assets/72678054/ff8cc65c-06b6-4c4e-9566-f57de50495f2)

**Comment by ZGGSONG** [comment]
请看我主页pin的某api项目

**Comment by ZGGSONG** [comment]
https://github.com/ZGGSONG/deepl-api
