### ISSUE TITLE
DEEPL用不上，写着too many requests

### ISSUE THREAD

**Issue by threekissgithub** [ZGGSONG/STranslate#41]
<img width="359" alt="deepl" src="https://github.com/ZGGSONG/STranslate/assets/57313035/f882a87a-3c8c-45ba-88b8-c76de1ba8cef">

**Comment by ZGGSONG** [comment]
[疑问 第二条](https://github.com/ZGGSONG/STranslate?tab=readme-ov-file#%E7%96%91%E9%97%AE)

更新最新版本，使用STranslate本地服务
