### ISSUE TITLE
希望可以增加快速切换翻译引擎功能

### ISSUE THREAD

**Issue by hujie12306** [ZGGSONG/STranslate#42]
因为部分Api效果好但收费高，大多数情况下我只使用免费的引擎，但偶尔需要切换收费高的引擎时需要进入设置打开服务，过于繁琐。最好可以在翻译界面实现切换。
Ps1:翻译界面最窄宽度感觉还是有点宽
Ps2:建议增加增量翻译功能。应用场景：PDF跨页翻译

**Comment by ZGGSONG** [comment]
> 对了，OPEN AI这种服务能实现切换promt的功能吗

当前最新版本不是有吗

**Comment by hujie12306** [comment]
> > 对了，OPEN AI这种服务能实现切换promt的功能吗
> 
> 当前最新版本不是有吗

我的意思是在翻译界面去切换，在设置里通常是一些比较固定的东西，但对prompt的需求实际上是善变的

**Comment by ZGGSONG** [comment]
> > > 对了，OPEN AI这种服务能实现切换promt的功能吗
> > 
> > 
> > 当前最新版本不是有吗
> 
> 我的意思是在翻译界面去切换，在偏好里设置通常是一些比较固定的东西，但对prompt的需求实际上是善变的

嗯嗯 考虑的挺好  下个版本跟上 不过 可能要改变当前prompt的设计了

**Comment by ZGGSONG** [comment]
close with commit (17060c8b93e214651cd5355660b8d4d8d7be2932)
