### ISSUE TITLE
功能建议：管理员权限是否可以以服务的方式来启动

### ISSUE THREAD

**Issue by iciness** [ZGGSONG/STranslate#45]
这样不用每次启动的时候弹uac

**Comment by ZGGSONG** [comment]
首先以服务方式运行不适用与拥有UI的客户端程序，其次UAC弹窗你个人不喜欢，完全可以通过修改 `更改用户帐户控制设置` 进行规避

**Comment by iciness** [comment]
可能理解错我的意思了，类似微软的powertoys，也有需要管理员权限，它自启获取管理员权限的方式就是起一个服务来获取

**Comment by ZGGSONG** [comment]
> 可能理解错我的意思了，类似微软的powertoys，也有需要管理员权限，它自启获取管理员权限的方式就是起一个服务来获取

刚安装 [0.79](https://github.com/microsoft/PowerToys/releases/download/v0.79.0/PowerToysSetup-0.79.0-x64.exe) 版本的PowerToys体验了一下管理员权限启动,不管手动`管理员权限重启`还是保存`以管理员权限启动`后重启依旧弹出UAC弹窗
