### ISSUE TITLE
窗口不自动关闭，非置顶

### ISSUE THREAD

**Issue by 372s** [ZGGSONG/STranslate#47]
翻译好的内容，鼠标移动到其他地方后，会自动关闭窗口，如果想过一会再看需要去查找记录才行，虽然有置顶功能，但会影响其他看软件内容

**Comment by ZGGSONG** [comment]
> 翻译好的内容，鼠标移动到其他地方后，会自动关闭窗口，如果想过一会再看需要去查找记录才行，虽然有置顶功能，但会影响其他看软件内容

唤醒软件界面还有
1. 双击托盘可在配置中修改为显示界面而不清空输入内容和结果
2. 显示界面全局热键(默认alt+g)，也不会清理信息仅唤醒界面
