### ISSUE TITLE
请求增加截图或者 ocr 功能的默认识别语言设置。

### ISSUE THREAD

**Issue by Xaries88** [ZGGSONG/STranslate#48]
能不能设置截图或者 ocr 功能的默认识别语言，e.g.:图片上都是俄语，但识别出来都是英文字母。

**Comment by ZGGSONG** [comment]
> 能不能设置截图或者 ocr 功能的默认识别语言，e.g.:图片上都是俄语，但识别出来都是英文字母。

当前OCR使用的[PaddleOCRSharp](https://gitee.com/raoyutian/PaddleOCRSharp)，模型仅能识别中英文和数字，其他语言的需要接入后续接入各大云OCR Api才能支持 #23

**Comment by Xaries88** [comment]
明白了，感谢！期待后续 API 的上线

**Comment by ZGGSONG** [comment]
close with commit (21320d458c17c3dfcab7429d06613d029dc15870)
