### ISSUE TITLE
请求历史记录页面增加快捷键支持。

### ISSUE THREAD

**Issue by Xaries88** [ZGGSONG/STranslate#49]
目前历史记录在设置下面，路径较深，且位置比较奇怪，建议加一个快捷键或者快捷操作图标方便快速打开。

个人意见，历史记录与设置是无关的，更应该放到主页面里面。

**Comment by ZGGSONG** [comment]
<img width="883" alt="image" src="https://github.com/ZGGSONG/STranslate/assets/49741009/4ced2ccc-2e9f-494d-ac3a-cbc674b2d092">

首先当前有一个主界面快捷入口的选项，默认关闭你自己打开保存一下就好，其次后续考虑给一个软件内快捷键。

> 除了OCR 只有两个页面，最重要的主体就是翻译！剩下的全在设置里，没必要在考虑别的页面
