### ISSUE TITLE
很不错的软件，但是没有截图功能

### ISSUE THREAD

**Issue by CAI5201314** [ZGGSONG/STranslate#50]
不过很可惜没有截图功能。
另外按多次alt+s会出现套娃情况

**Comment by ZGGSONG** [comment]
1. 截图功能有很多成熟的软件snipaste、pixpin等等，个人精力有限，目前没有时间去做这方面的开发，当然不排除以后有时间去研究研究

2. 套娃bug已经解决 (76c1825489ad86b080b56c3baff2cbe07d75b7d1)
