### ISSUE TITLE
希望OpenAI翻译添加上下文功能

### ISSUE THREAD

**Issue by 17794** [ZGGSONG/STranslate#51]
希望OpenAI翻译添加上下文功能，有时翻译需要给AI上下文才可以翻译的更好，因为上下文定义了术语和一些名词的解释。而且希望能有一个配置项文件，因为key可能常常更换，通过添加配置项文件可以大大减少在不同电脑上实现相同配置的时间。

**Comment by ZGGSONG** [comment]
定义术语部分其实就是prompt，这部分在功能上本质上就是导出导入配置的问题，这个功能 (fddb3be9af5c9b389e95db1e171c41cf64cd463a) 已经实现了，下个版本发布
