### ISSUE TITLE
软件交互过程的一些问题和建议。

### ISSUE THREAD

**Issue by somaicro** [ZGGSONG/STranslate#52]
1. 翻译界面存在的时候，使用**截图翻译**和**文字识别**，界面不会隐藏而挡住画面。
2. 在原有交互基础上，**显示界面**功能，建议一键显示/隐藏。右手能够做其他事情，操作会更好，而不用去点鼠标或者隔开按esc。
3. **截图翻译**和**文字识别**，使用过程中，重复快捷键会存在套娃现象。
4. 因为识别不一定符合期望形式，希望翻译输入框能够自由编辑，例如能够手动换行等操作。ALT+Enter可以作为换行，原来的强制翻译可以指定为快捷键，由用户自定义。

**Comment by ZGGSONG** [comment]
1. 由于添加了翻译界面动画，导致翻译界面触发截图导致无法正常隐藏，前些天已经发现并解决，下个版本发布
2. 显示界面 目前有全局快捷键(默认`Alt`+`G`)，不过你提到的触发显示，如果已经显示了再次触发则隐藏挺不错，下个版本添加一个可配置项吧
3. 已修复(76c1825489ad86b080b56c3baff2cbe07d75b7d1)
4. 留有Shift+Enter作为换行，强制翻译Ctrl+Enter，软件内快捷键目前不开放用户自定义。
<img width="383" alt="image" src="https://github.com/ZGGSONG/STranslate/assets/49741009/fb8a1d7d-d624-4b29-a280-26dcd35144ae">

**Comment by somaicro** [comment]
好勒 辛苦了，期待更新。
