### ISSUE TITLE
Mac版本那时候开发啊

### ISSUE THREAD

**Issue by qqlcx5** [ZGGSONG/STranslate#54]
让我用7年前的mac 也能用上

**Comment by ZGGSONG** [comment]
WPF is a .NET Core UI framework for building Windows desktop applications.
(WPF 是用于构建 Windows 桌面应用程序的 .NET Core UI 框架)

-- [WPF-Github](https://github.com/dotnet/wpf)


mac 推荐 Bob，大家都是抄的 [Bob](https://bobtranslate.com/)

**Comment by suibianzai** [comment]
mac还可以用easydict，开源免费，也是仿Bob的
