### ISSUE TITLE
请问截图翻译为何无法识别选定语种

### ISSUE THREAD

**Issue by anatoliux2233** [ZGGSONG/STranslate#56]
已经将语言设置为俄语和简体中文，但截图翻译总是识别为英语
![微信截图_20240416224053](https://github.com/ZGGSONG/STranslate/assets/38915367/17307d66-c5b2-47ce-ad49-928ba5d95ddd)

**Comment by ZGGSONG** [comment]
> 已经将语言设置为俄语和简体中文，但截图翻译总是识别为英语 ![微信截图_20240416224053](https://private-user-images.githubusercontent.com/38915367/322887582-17307d66-c5b2-47ce-ad49-928ba5d95ddd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzMTU2NjMsIm5iZiI6MTcxMzMxNTM2MywicGF0aCI6Ii8zODkxNTM2Ny8zMjI4ODc1ODItMTczMDdkNjYtYzViMi00N2NlLWFkNDktOTI4YmE1ZDk1ZGRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDAwNTYwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4Nzg1NTk1MjNiM2JmMjgzZmZiNTY3ODVjZGFhOGJlODY2YmNkZjZlMTQ3NTViOTc1NzI2NzZmY2M0YjMwZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wc5lFmEqGxjsYnl4G8utnrfixSpDND92yKZpDOWs8xE)

当前最新release中仅支持paddleocr仅支持中英文数字组合识别，下个版本适配了多种在线ocr api支持多种语言
