### ISSUE TITLE
问题建议

### ISSUE THREAD

**Issue by guzzhao** [ZGGSONG/STranslate#57]
1. 升级之后内存占用明显增大,而且出现窗口关闭,但在任务管理器里显示在前台(运行软件且未使用)
2. 希望发布到scoop

**Comment by ZGGSONG** [comment]
1. 内存增大这个问题我后续慢慢优化；窗口关闭现版本是执行动画将透明度降为0，并在动画执行结束后触发事件，事件中将界面隐藏，在我这边并没有发现保留在任务管理器前台的现象
2. windows包管理器没有使用过，先调研下

**Comment by guzzhao** [comment]
> 1. 内存增大这个问题我后续慢慢优化；窗口关闭现版本是执行动画将透明度降为0，并在动画执行结束后触发事件，事件中将界面隐藏，在我这边并没有发现保留在任务管理器前台的现象
> 2. windows包管理器没有使用过，先调研下

运行软件并且打开<启动时隐藏主界面>,如果不使用会一直在前台

**Comment by ZGGSONG** [comment]
> > 1. 内存增大这个问题我后续慢慢优化；窗口关闭现版本是执行动画将透明度降为0，并在动画执行结束后触发事件，事件中将界面隐藏，在我这边并没有发现保留在任务管理器前台的现象
> > 2. windows包管理器没有使用过，先调研下
> 
> 运行软件并且打开<启动时隐藏主界面>,如果不使用会一直在前台

只有在开启<启动时隐藏主界面>功能时，且没有使用的情况下会在任务管理器中显示在前台，后续调用挂起就不会了，是因为在检查配置是否隐藏界面时没有手动隐藏界面，这个加一行代码就行

**Comment by ZGGSONG** [comment]
https://github.com/chawyehsu/dorado/pull/838

**Comment by guzzhao** [comment]
使用scoop安装不能正常启动,需要删除配置文件后才能启动(AppData\Local\STranslate)
使用scoop安装的程序配置文件应该在scoop\persist下面,

 @ZGGSONG

**Comment by ZGGSONG** [comment]
1. 配置文件路径是写死的
2. 你说的这个情况，可能是配置文件变动比较大，读取时出现了问题，如果出现读取出错应该会以默认配置启动软件，并在配置目录以当前时间命名备份当前配置
3. 我也有在用scoop管理STranslate，没有遇到该问题，很大概率是2，具体的你可以把log信息拉出来看一下
