### ISSUE TITLE
Question about google api endpoint

### ISSUE THREAD

**Issue by nanoia** [ZGGSONG/STranslate#6]
What is the solution used to implement the google api, is there a code reference or can it be deployed self-hosted?

**Comment by ZGGSONG** [comment]
That's what the public service writes after parsing the packet. There are a lot of public services to try, such as bing, google, yandex's, some details part of the checksum calculation can refer to this project: [https://github.com/UlionTse/translators/](https://github.com/UlionTse/translators/)

**Comment by ZGGSONG** [comment]
Come to think of it wrote a version of go that packaged a windows executable for you
[google_translate.zip](https://github.com/ZGGSONG/STranslate/files/12075461/google_translate.zip)

**Comment by nanoia** [comment]
> This is achieved by Google Public Services parsing packets to build their own services. There are a lot of public services to try, such as bing, google, yandex's, some details part of the checksum calculation can refer to this project: https://github.com/UlionTse/translators/

Thank you for your reply, it helps a lot!
