### ISSUE TITLE
功能反馈 

### ISSUE THREAD

**Issue by somaicro** [ZGGSONG/STranslate#61]
![PixPin_2024-04-23_14-16-29](https://github.com/ZGGSONG/STranslate/assets/78190486/dcdb6008-be35-4c99-a7c8-3cff015fa55c)
更新了最新版本，截图的时候，主界面没有自动隐藏。

**Comment by ZGGSONG** [comment]
我的设计是热键启动截图不主动修改窗口状态，如果是在窗口快捷按钮启动截图，则会更新窗口状态成隐藏状态
![image](https://github.com/ZGGSONG/STranslate/assets/49741009/2b69e878-8bbf-4bb5-9807-2e1e9d742e83)
