### ISSUE TITLE
添加命令行调用

### ISSUE THREAD

**Issue by PiscesDreamer** [ZGGSONG/STranslate#62]
希望作者大大能考虑添加命令行调用的功能.
另外ocr识别的语言能否考虑加入日语识别

**Comment by ZGGSONG** [comment]
1. 命令行调用以及集成一样调用需要设计API，这个后面再开发
2. 看了下百度、腾讯OCR都支持日语的呀，软件都接入了

**Comment by PiscesDreamer** [comment]
> 1. 命令行调用以及集成一样调用需要设计API，这个后面再开发
> 2. 看了下百度、腾讯OCR都支持日语的呀，软件都接入了

我在用1.0.8版本,服务设置好像没有专门的ocr设置吧, 另外我说的是离线ocr能否识别日文,像那个umi-ocr一样.
命令行调用希望能尽快开发出来. 整体使用下来蛮流畅的.

**Comment by ZGGSONG** [comment]
那升级吧，现在升到1.1.0了，离线OCR当前的模型仅支持中英文数字以及标点，离线的目前暂时不考虑扩充了，主要是识别效果，少有能够超过paddleocr的，命令行功能我尝试开发一下吧

**Comment by ZGGSONG** [comment]
> 希望作者大大能考虑添加命令行调用的功能

很想了解一下命令行调用的目的是什么，我能想到的顶多就是命令行翻译了，还有哪些使用场景，OCR将结果输出到命令行？TTS读文本？给个参考，个人命令行用的不多，不了解痛点

**Comment by PiscesDreamer** [comment]
> > 希望作者大大能考虑添加命令行调用的功能
> 
> 很想了解一下命令行调用的目的是什么，我能想到的顶多就是命令行翻译了，还有哪些使用场景，OCR将结果输出到命令行？TTS读文本？给个参考，个人命令行用的不多，不了解痛点

我个人的想法是为了避免设置快捷键会出现快捷键冲突,因为我有在使用ahk写的软件,可以快速调用命令行.,这样就不需要设置全局快捷键了.
其他的命令行应用场景,我也不是了解的很清楚,但是比如snipaste, pot这样的软件作者都提供了类似的命令行调用,
可能是方便了一些高级应用场景.至少方便其他软件调用这点是没错的.

**Comment by ZGGSONG** [comment]
9edc7f9523d547051eebfed300ef8d6a03c889ad

**Comment by ZGGSONG** [comment]
> [9edc7f9](https://github.com/ZGGSONG/STranslate/commit/9edc7f9523d547051eebfed300ef8d6a03c889ad)

https://github.com/ZGGSONG/STranslate/releases/tag/1.1.1.508
