### ISSUE TITLE
Error:请求出错: The SSL connection could not be established, see inner exception.

### ISSUE THREAD

**Issue by maktiny** [ZGGSONG/STranslate#65]
当使用划词翻译时报错：请求出错: The SSL connection could not be established, see inner exception.

**Comment by ZGGSONG** [comment]
网络问题，请检查网络连接

**Comment by maktiny** [comment]
网络连接没i问题i，浏览器能正常上网，只是使用公司内网wifi，这需要其他的配置吗？没有使用代理

**Comment by ZGGSONG** [comment]
https://github.com/ZGGSONG/STranslate/discussions/46

**Comment by maktiny** [comment]
通过划词翻译， googel翻译，deepL和爱词霸都报同样的错误，The SSL connection could not be established, see inner exception.

**Comment by ZGGSONG** [comment]
> 通过划词翻译， googel翻译，deepL和爱词霸都报同样的错误，The SSL connection could not be established, see inner exception.

这两个服务都在 deno.dev上，国内访问比较玄学
https://deeplx.deno.dev/
https://googlet.deno.dev/

推荐添加使用本地服务STranslate
