### ISSUE TITLE
[FR] 添加飞书 ocr 以及 翻译 接口

### ISSUE THREAD

**Issue by ccddos** [ZGGSONG/STranslate#67]
免费，质量高，国内直连，只需要自己申请一个应用获取 id和key就行

ocr相关文档
https://open.feishu.cn/document/server-docs/ai/optical_char_recognition-v1/basic_recognize

翻译相关文档
https://open.feishu.cn/document/server-docs/ai/translation-v1/translate

鉴权文档
https://open.feishu.cn/document/server-docs/authentication-management/access-token/tenant_access_token_internal

创建应用
https://open.feishu.cn/app?lang=zh-CN

**Comment by waxingren** [comment]
使用起来跟百度有啥区别吗  还是质量好点

**Comment by ZGGSONG** [comment]
飞书需要购买企业服务才能调用api，我无法调试，无法确保功能是否正常上线。
如果能提供一个临时的secrectID、Key调试，我将继续开发并上线该功能。

如果可行，通过[邮箱](mailto:zggsong@foxmail.com)联系我，不认可请关闭该issue

![image](https://github.com/ZGGSONG/STranslate/assets/49741009/00183310-5e2b-412c-9ca1-7aea65c85801)
![image](https://github.com/ZGGSONG/STranslate/assets/49741009/805caf5e-11af-4d75-9a11-ffe9449a9840)

**Comment by ccddos** [comment]
不好意思，没注意到飞书已经关闭了相关免费api，我前年使用的时候还行。。。打扰了
