### ISSUE TITLE
[FR] remember & auto-"remove line breaks" for new text

### ISSUE THREAD

**Issue by Owyn** [ZGGSONG/STranslate#69]
Make "remove line-breaks" a toggle option as well (another button for it at the top of the window), so it would **always** auto-remove line breaks before translating please, 

because now I have to always press this button and then press "Enter" to make it translate again but better, 

else it's all weird if it's on multi-line:
![image](https://github.com/ZGGSONG/STranslate/assets/1309656/11c8b4d0-e2c3-490b-aeab-f945468d046d)

**Comment by Owyn** [comment]
I have found the setting in the options menu but still - a quick way to toggle it from the main menu would be nice, because for some materials - it is essential - while for others it will be a hindrance and we have to change it for those

**Comment by ZGGSONG** [comment]
I will add a shortcut switch for the main interface in the next version.
