### ISSUE TITLE
How can I change its language and question about deepl

### ISSUE THREAD

**Issue by toprak** [ZGGSONG/STranslate#7]
do you use deeplx as deepl api? if you not it would be good if you add it.

**Comment by toprak** [comment]
also i guess it does not support new deepl languages such as turkish

**Comment by ZGGSONG** [comment]
deeplx is not a plugin for bob, essentially a group packet forwarding middleware, support for specific format data, my api is the official interface, if you are interested you can look at [link](https://github.com/ZGGSONG/deepl-api), in addition to the current inspiration about these similar open source projects basically from an article in zu1k

**Comment by toprak** [comment]
@ZGGSONG that's very nice, can you add new languages to it? deepl added turkish and some language too

**Comment by ZGGSONG** [comment]
https://github.com/ZGGSONG/STranslate/releases/tag/0.28
