### ISSUE TITLE
新版本如何清空热键

### ISSUE THREAD

**Issue by EyoungShieh1992** [ZGGSONG/STranslate#70]
如题，旧版本能清空热键，新版本不行，按Backs和Delete键都不行
![image](https://github.com/ZGGSONG/STranslate/assets/31103392/2271c119-bdc4-4cfa-b856-3979907c3d75)

**Comment by ZGGSONG** [comment]
新增单字符全局热键支持的时候引起的问题，已修复(48dc869)
