### ISSUE TITLE
电脑外接副屏无法识别翻译、无法ocr

### ISSUE THREAD

**Issue by TJNOV** [ZGGSONG/STranslate#72]
如题

**Comment by ZGGSONG** [comment]
鼠标移动至你想要截图的显示器  用热键触发

**Comment by TJNOV** [comment]
是的，可以框选界面内容，但是没有任何东西弹出

**Comment by ZGGSONG** [comment]
软件目录下的log文件，把日志贴一下看看

**Comment by TJNOV** [comment]
2024-05-09 15:32:24.051 [INF] STranslate Closed...
2024-05-09 15:35:08.432 [INF] STranslate Opened...
2024-05-09 19:04:04.870 [INF] STranslate Closed...
2024-05-09 19:06:09.355 [INF] STranslate Opened...

找到原因了！笔记本屏幕分辨率较高，缩放是200%；外接显示器分辨率较低，缩放是100%。当设置为相同的175%后，软件就正常使用了。

此外，如果把**外接显示器设置为主屏幕**，即使**屏幕缩放不同**，软件也可以**正常使用**。

只有在**笔记本屏幕设置为主屏幕**，**屏幕缩放不同**，软件只有主屏幕可用，**外接显示屏幕软件不可用**。（但是这种情况是最普遍的）

_😂_

**Comment by ZGGSONG** [comment]
你这种调分辨率和缩放顶多是影响软件截图的时候，截图贴出来的有偏移。而这个问题我在开发的时候发现是windows多显示器修改分辨率后底层一些数据没有刷新导致的，要么切换以后重新插拔一下外接显示器，要么切换完了以后重启一下电脑，这个真的很坑

**Comment by TJNOV** [comment]
有时候是又便宜的弹出窗口，但是刚才这一段时间，都是不弹窗口。
在打开”常规设置--》非常规屏幕截图修复“后，上述问题没有解决，出现新问题，如下图：
![PixPin_2024-05-09_20-23-29](https://github.com/ZGGSONG/STranslate/assets/76683201/57dfca51-0a78-4e33-8c08-8a3fceaf6235)

**Comment by ZGGSONG** [comment]
你把`非常规屏幕截图修复`这个关掉，修改好多显示器缩放后重启电脑 再试试

**Comment by ZGGSONG** [comment]
> 都是不弹窗口。

这是啥意思  你指下面这个窗口？

![image](https://github.com/ZGGSONG/STranslate/assets/49741009/f33ecf80-c4ad-420a-b666-22b5608b2a86)

**Comment by BaoYier** [comment]
> 2024-05-09 15:32:24.051 [INF] STranslate Closed... 2024-05-09 15:35:08.432 [INF] STranslate Opened... 2024-05-09 19:04:04.870 [INF] STranslate Closed... 2024-05-09 19:06:09.355 [INF] STranslate Opened...
> 
> 找到原因了！笔记本屏幕分辨率较高，缩放是200%；外接显示器分辨率较低，缩放是100%。当设置为相同的175%后，软件就正常使用了。
> 
> 此外，如果把**外接显示器设置为主屏幕**，即使**屏幕缩放不同**，软件也可以**正常使用**。
> 
> 只有在**笔记本屏幕设置为主屏幕**，**屏幕缩放不同**，软件只有主屏幕可用，**外接显示屏幕软件不可用**。（但是这种情况是最普遍的）
> 
> _😂_

感谢，姑且用切换主屏幕的方法解决了，在MAC也有相同的问题，Pot版本3.0.5.

另外Bob和Easydict不会出这个问题。

**Comment by ZGGSONG** [comment]
这个可能跟底层获取屏幕分辨率有关系，我调试的时候发现好几次获取得显示器逻辑分辨率不同，最后我加了一个软件热键Ctrl Shift M回到主屏幕中间，就是你双击托盘软件是打开的，只是有时候计算的位置不太对，超出屏幕显示范围(虽然后台有计算，超出就会到屏幕中间，可能会失效，上面也说了)，直接用热键即可触发回到屏幕中间。

此外也增加了配置是否使用上次关闭时的位置，可以手动开启关闭
