### ISSUE TITLE
其他语言OCR翻译

### ISSUE THREAD

**Issue by ZShuai95** [ZGGSONG/STranslate#73]
希望能增加俄语OCR识别翻译

**Comment by ZGGSONG** [comment]
腾讯、百度OCR都支持的呀，PaddleOCR是因为没有模型不支持，飞浆官方也没有看到有俄语的模型

![image](https://github.com/ZGGSONG/STranslate/assets/49741009/0781cd17-b1ff-4b04-8cd5-0dc168a7ba27)
![image](https://github.com/ZGGSONG/STranslate/assets/49741009/c62acb23-1d57-46ea-bb05-34464abd8750)
