### ISSUE TITLE
语音播放没有声音

### ISSUE THREAD

**Issue by yage-zhu** [ZGGSONG/STranslate#74]
我的是win11系统，内置的语言播放点的没有反应没有声音，卸载后试了旧版本也不行，用虚拟机的win7装了后也不行，试了很久一直都播放不了，不知道什么原因。

**Comment by ZGGSONG** [comment]
具体的系统版本号像下面一样提供一下：
![image](https://github.com/ZGGSONG/STranslate/assets/49741009/ae636f59-92c5-456b-b0e5-f2c4e8206e79)

**Comment by yage-zhu** [comment]
![image](https://github.com/ZGGSONG/STranslate/assets/97264644/547ad45c-e5a5-415f-a45b-f8955da4aafa)

**Comment by ZGGSONG** [comment]
我用装了一台Win11 23H2 版本的系统，并没有发现有什么异常呀，正常可用

你要不看下软件根目录下的日志文件，有没有异常

**Comment by yage-zhu** [comment]
找到原因了，安装的不忘初心系统，语音识别TTS被精简掉了，非常感谢。
