### ISSUE TITLE
启用单文件发布

### ISSUE THREAD

**Issue by emako** [ZGGSONG/STranslate#75]
![image](https://github.com/ZGGSONG/STranslate/assets/24737061/dc948df1-4ea9-4d16-ab6a-d92d714fae34)

希望能启用单文件发布，可以大大减少发包里文件数量

**Comment by ZGGSONG** [comment]
可以，以前发现过以这种方式打包出现一系列问题，就一直没用。

尝试了一下[Fody-Costura](https://github.com/Fody/Costura) 成功打包。

下个版本将以该方式打包发布

**Comment by ZGGSONG** [comment]
> .NET 8下应该不会出问题吧，我记得AOT才会出问题。
> 
> Fody的话能手动剔除非托管库也行。

试了一下，发现以单文件发布的情况下部分库获取的结果都不太一样，导致一些功能异常

6c2ffe2

**Comment by ZGGSONG** [comment]
> 哪个功能受影响了，我可以测测看，或者手动排除

蟹蟹，不过我已经修复了

![image](https://github.com/ZGGSONG/STranslate/assets/49741009/690acbd4-8521-4dc3-99fd-fa33c553e2b2)

(6c2ffe2cddb7eb766d1ad8c04e7aef1e93f51e20)

如果在启用用这个去获取程序集名称单文件发布会得到空值


另外，在[文章](https://zhuanlan.zhihu.com/p/689871389?utm_id=0)中发现，如果再开启`IncludeAllContentForSelfExtract`最后打包出来只有一个exe，但是更多函数会受到影响，并且只是在运行时把原本的文件解压缩运行在`用户/appdata/local/tmp/.net/STranslate`下

**Comment by emako** [comment]
PaddleOCRSharp大是应为支持多语言的原因？
在https://github.com/babalae/better-genshin-impact里用也就17MB
![image](https://github.com/ZGGSONG/STranslate/assets/24737061/2a5058bd-20e0-4a7b-ad0c-d4bd6ed2300b)

**Comment by ZGGSONG** [comment]
![image](https://github.com/ZGGSONG/STranslate/assets/49741009/dc87c350-4ca1-499d-bcb4-bfc12b3a34f8)

>> [PaddleOOCRSharp](https://gitee.com/raoyutian/PaddleOCRSharp/tree/dev/PaddleOCRSharp/PaddleOCRLib)

**Comment by emako** [comment]
模型不一样，https://github.com/sdcb/PaddleSharp

**Comment by ZGGSONG** [comment]
模型的话我适配了中英日韩也有50MB，周杰这个我集成过，效果一般，并且速度比较慢，https://gitee.com/raoyutian/PaddleOCRSharp 这个项目针对paddleocr做了很多优化，起码比我直接用官方的库去做优化好太多了 就是用的库比较多 比较占空间  但是总体来说还是体验放在第一位

**Comment by emako** [comment]
我也试试看
