### ISSUE TITLE
增加显示界面时即置顶的设置选项

### ISSUE THREAD

**Issue by PiscesDreamer** [ZGGSONG/STranslate#76]
不想每次置顶都点击图钉图标, 希望可以更方便的置顶界面窗口.

**Comment by ZGGSONG** [comment]
ctrl shift q

**Comment by PiscesDreamer** [comment]
> ctrl shift t 连续移位试验
哦哦, 快捷键设置那块没有这个选项,我还以为没有这个功能

**Comment by ZGGSONG** [comment]
https://stranslate.zggsong.com/docs/#软件内快捷键
