### ISSUE TITLE
[feature] Setup安装包

### ISSUE THREAD

**Issue by emako** [ZGGSONG/STranslate#80]
目前看没有打包成安装包形式，有做的打算吗？

有的话，推介一款我做的安装包：可下载EXE看到安装包运行，https://github.com/babalae/better-genshin-impact/releases
![image](https://github.com/ZGGSONG/STranslate/assets/24737061/709aee64-c26a-4f46-81cf-6454e50f46e2) 我这边可以contribute

或者也可以用微软商店的证书挂MSIX安装包

**Comment by ZGGSONG** [comment]
个人不太喜欢`Setup`方式，包管理器，类似于[Scoop](https://github.com/ScoopInstaller/Scoop)这种比较明了的方式我可能更加推崇

**Comment by ZGGSONG** [comment]
> 我这边可以contribute

没看到这条，你可以提PR

**Comment by emako** [comment]
现在设计的Setup是源码编译，打算升级成工具构建再提交

**Comment by ZGGSONG** [comment]
好的

**Comment by emako** [comment]
久等了，目前MicaSetup v2.3.0起支持命令行编译 https://github.com/lemutec/MicaSetup/releases/tag/v2.3.0
