### ISSUE TITLE
优化OpenAI服务绑定与翻译触发机制

### ISSUE THREAD

**Issue by whz-pku** [ZGGSONG/STranslate#81]
两个功能建议：1.openai如果设置多个服务的话，服务的prompt貌似是绑定的，所以设定多个openai服务无效。2.openai api比较贵，所以希望折叠的话能不要自动开始翻译，打开折叠后再开始翻译会比较好

**Comment by ZGGSONG** [comment]
1. 确实是个bug，只有在添加的时候会出现，下个版本修复
2. 打开折叠这个建议可以，下个版本添加
