### ISSUE TITLE
每次关闭软件微软tts的声音就会重置为0

### ISSUE THREAD

**Issue by yage-zhu** [ZGGSONG/STranslate#82]
![Uploading SOS{ZR{SXL9663A(N(FI]FQ.png…]()
每次微软tts都换为其他声音，但软件一打开，都是默认第一个声音（晓北-东北话）。发现是每次关闭软件的时候，配置文件会保存一次，把voice重置为0了。

**Comment by yage-zhu** [comment]
![QQ图片20240521093643](https://github.com/ZGGSONG/STranslate/assets/97264644/7a364074-41ca-465c-9324-63ae6717e6e0)

**Comment by ZGGSONG** [comment]
已修复，下个版本发布此更新(17599ee4ff6e04592de5aa46a5ab42d773b8f810)
