### ISSUE TITLE
软件内更新后打不开，（组件已下载）显示下载.NET组件窗口

### ISSUE THREAD

**Issue by GEEKCX** [ZGGSONG/STranslate#84]
.NET组件下载安装了数次，仍无法运行，每次更新需卸载重新安装。

**Comment by GEEKCX** [comment]
另外可以的话，clash verge rev 的升级方式很舒适~可以参考一下

**Comment by ZGGSONG** [comment]
> .NET组件下载安装了数次，仍无法运行，每次更新需卸载重新安装。

1. 你下载的具体是什么，安装好后无法运行的话那么你可能下载错了组件；
2. `每次更新需卸载重新安装` 是什么意思，所以是能打开还是一直打不开

> 软件内下载的是需要.NET8 Runtime的版本，独立版本需要到Release手动下载`SelfContained`字样的版本

最顺滑的方式是安装.NET8 Runtime，使用Scoop管理软件或者用软件内升级方式(后面这个我可能不太想维护，大概率维持现状)

**Comment by ZGGSONG** [comment]
> 另外可以的话，clash verge rev 的升级方式很舒适~可以参考一下

我回头有空看看

**Comment by GEEKCX** [comment]
![image](https://github.com/ZGGSONG/STranslate/assets/31879429/5c2ce637-4b01-492e-a677-6496d054afa7)
奇怪啊，安装后还是不行，家里和公司都是一样的问题，https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-8.0.300-windows-x64-installer

**Comment by ZGGSONG** [comment]
https://dotnet.microsoft.com/zh-cn/download/dotnet/thank-you/runtime-desktop-8.0.5-windows-x64-installer

**Comment by GEEKCX** [comment]
> https://dotnet.microsoft.com/zh-cn/download/dotnet/thank-you/runtime-desktop-8.0.5-windows-x64-installer

![Clip_2024-05-21_16-40-10](https://github.com/ZGGSONG/STranslate/assets/31879429/3ad7cb0e-229d-4049-8012-f1fca8747e84)
不行，更新的话还是先导出配置，删除重新下载吧。

**Comment by ZGGSONG** [comment]
![image](https://github.com/ZGGSONG/STranslate/assets/49741009/a1c88d5d-e652-4528-ae69-8c8b0f1b74c8)

我装了台全新的win10，只装了一个desktop runtime 下载了最新的1.1.3.514版本 没有复现这个问题

**Comment by GEEKCX** [comment]
> ![image](https://private-user-images.githubusercontent.com/49741009/332466878-a1c88d5d-e652-4528-ae69-8c8b0f1b74c8.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzMDI1ODYsIm5iZiI6MTcxNjMwMjI4NiwicGF0aCI6Ii80OTc0MTAwOS8zMzI0NjY4NzgtYTFjODhkNWQtZTY1Mi00NTI4LWFlNjktOGM4YjBmMWI3NGM4LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMVQxNDM4MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNjdiOWNkNzI1OTE4Y2MwZjE0YTY5ZjQ2ODdkNjA5NDY4MDAzZDM0YzM2NWZhMTg5NzJhZWFmM2MwYTM2ZDE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.W6xLyVng1HhPCuA5sqmBvg5Jhyy__Ip-hHLCzvtjrgw)
> 
> 我装了台全新的win10，只装了一个desktop runtime 下载了最新的1.1.3.514版本 没有复现这个问题

好的，我再找找我这边的问题。感谢开发者

**Comment by ZGNCZMY** [comment]
同样的问题

**Comment by ZGGSONG** [comment]
> 同样的问题,解压文件覆盖才行

也是只有SelfContained版本才能运行？

**Comment by GEEKCX** [comment]
> ![image](https://private-user-images.githubusercontent.com/49741009/332466878-a1c88d5d-e652-4528-ae69-8c8b0f1b74c8.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNTY2ODIsIm5iZiI6MTcxNjM1NjM4MiwicGF0aCI6Ii80OTc0MTAwOS8zMzI0NjY4NzgtYTFjODhkNWQtZTY1Mi00NTI4LWFlNjktOGM4YjBmMWI3NGM4LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMlQwNTM5NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMTAyNzVlZGE0ZTM1MjY4MzUxNjUzODBmNzEwYWQwMzQ0ZTQ1YzgwZWNlZDc2NWY5OTliMjkyMmQ1YjM2NjM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lT3Zxa8KSncSoJriPfXdRZSTPqAQ6hosKQccfv4pjpU)
> 
> 我装了台全新的win10，只装了一个desktop runtime 下载了最新的1.1.3.514版本 没有复现这个问题

装个旧版然后软件内更新试过了么？

**Comment by ZGNCZMY** [comment]
> > 同样的问题,解压文件覆盖才行
> 
> 也是只有SelfContained版本才能运行？

一直在用这个版本，其他的不知道，覆盖之后主程序右键用管理员权限启动

**Comment by ZGGSONG** [comment]
> > > 同样的问题,解压文件覆盖才行
> > 
> > 
> > 也是只有SelfContained版本才能运行？
> 
> 一直在用这个版本，其他的不知道，覆盖之后主程序右键用管理员权限启动

那不一样 你一直用独立版本，那么你电脑上大概率是没有装.net8 desktop runtime前者是装了runtime还是无法正常启动依赖runtime的版本

**Comment by GEEKCX** [comment]
【已解决】下了不带self版本，可以下载旧版吗可以正常更新不会弹出（.net组件窗口）

**Comment by ZGNCZMY** [comment]
> > > > 同样的问题,解压文件覆盖才行
> > > 
> > > 
> > > 也是只有SelfContained版本才能运行？
> > 
> > 
> > 一直在用这个版本，其他的不知道，覆盖之后主程序右键用管理员权限启动
> 
> 那不一样 你一直用独立版本，那么你电脑上大概率是没有装.net8 desktop runtime前者是装了runtime还是无法正常启动依赖runtime的版本
已有.NET 8.0 SDK (v8.0.300) - Windows x64
程序配置文件清空之后
解压STranslate_1.0.9.417_win-x64_self_contained打开设置好开机启动和管理员然后在线升级提示issue的问题
再解压STranslate_1.1.3.514_win-x64_self_contained_7z覆盖右键主程序管理员启动才能正常打开程序，开机启动也有问题

**Comment by ZGGSONG** [comment]
> 解压STranslate_1.0.9.417_win-x64_self_contained打开设置好开机启动和管理员然后在线升级提示issue的问题

self_contained版本不带软件内置升级功能！

> 再解压STranslate_1.1.3.514_win-x64_self_contained_7z覆盖右键主程序管理员启动才能正常打开程序，开机启动也有问题

开机启动功能的逻辑是将当前主程序`STranslate.exe`路径的创建一个软连接(快捷方式)到用户开机启动目录，如果主程序路径有变动，开机启动功能会失效
> win + r => shell:startup

**Comment by ZGGSONG** [comment]
> 【已解决】下了不带self版本，测试下载旧版可以正常通过软件内更新，不会弹出（.net组件窗口）

因为 1.1.3.514 版本大幅精简了动态链接库(dll)数量，建议全新下载直接覆盖，直接升级的方式会覆盖，但是这样就存在大量多余且未使用的dll，不知道这样有没有影响，虽然我本地测试是没有问题，但每个人运行环境不同，不好说

**Comment by ZGNCZMY** [comment]
> > 解压STranslate_1.0.9.417_win-x64_self_contained打开设置好开机启动和管理员然后在线升级提示issue的问题
> 
> self_contained版本不带软件内置升级功能！
> 
> > 再解压STranslate_1.1.3.514_win-x64_self_contained_7z覆盖右键主程序管理员启动才能正常打开程序，开机启动也有问题
> 
> 开机启动功能的逻辑是将当前主程序`STranslate.exe`路径的创建一个软连接(快捷方式)到用户开机启动目录，如果主程序路径有变动，开机启动功能会失效
> 
> > win + r => shell:startup

开机自启之前弄好了，我是看到关于那边有检查更新功能点了升级，哈哈😄️

**Comment by ZGGSONG** [comment]
> 开机自启之前弄好了，我是看到关于那边有检查更新功能点了升级，哈哈😄️

发现最新版启用单文件发布后开机自启功能失效，已修复(083243fb331d9f2ad4ef4799b42284d1bea781f5)

> 微软留下的坑 [IL3001：当发布为单个文件时，避免访问程序集文件路径](https://learn.microsoft.com/zh-cn/dotnet/core/deploying/single-file/warnings/il3001)

**Comment by ZGNCZMY** [comment]
> > 开机自启之前弄好了，我是看到关于那边有检查更新功能点了升级，哈哈😄️
> 
> 发现最新版启用单文件发布后开机自启功能失效，已修复([083243f](https://github.com/ZGGSONG/STranslate/commit/083243fb331d9f2ad4ef4799b42284d1bea781f5))
> 
> > 微软留下的坑 [IL3001：当发布为单个文件时，避免访问程序集文件路径](https://learn.microsoft.com/zh-cn/dotnet/core/deploying/single-file/warnings/il3001)

 看到问题发现后有关于开机自启的代码更新，有修复后的release版本发布吗

**Comment by ZGGSONG** [comment]
> > > 开机自启之前弄好了，我是看到关于那边有检查更新功能点了升级，哈哈😄️
> 
> > 
> 
> > 发现最新版启用单文件发布后开机自启功能失效，已修复([083243f](https://github.com/ZGGSONG/STranslate/commit/083243fb331d9f2ad4ef4799b42284d1bea781f5))
> 
> > 
> 
> > > 微软留下的坑 [IL3001：当发布为单个文件时，避免访问程序集文件路径](https://learn.microsoft.com/zh-cn/dotnet/core/deploying/single-file/warnings/il3001)
> 
> 
> 
>  看到问题发现后有关于开机自启的代码更新，有修复后的release版本发布吗


又修复了一些别的问题和优化，晚上先发布一个版本修复问题吧，feature以后再发

**Comment by hhhllll888** [comment]
解决了，我电脑复现了，死活打不开，但是我自己工作电脑可以打开，我发现把电脑上的dotnet环境卸载就可以了，看下自己电脑是不是有其他的dotnet环境，或者7.0,6.0的那种，卸载掉就可以打开了
