### ISSUE TITLE
OCR本地识别文字，韩语识别不了

### ISSUE THREAD

**Issue by CN-Patrick** [ZGGSONG/STranslate#86]

**Comment by CN-Patrick** [comment]
而且为什么不开代理完全不能翻译啊，不是可以离线翻译嘛

**Comment by ZGGSONG** [comment]
1. PaddleOCR支持中英日韩、且自动模式仅支持中英数字，日韩需要手动去OCR页面手动指定，其使用的不是同一模型，PaddleOCR日韩离线识别仅支持在OCR页面启用，热键截图翻译仅支持OCR自动模式

![image](https://github.com/ZGGSONG/STranslate/assets/49741009/16d37b25-331e-47c0-9992-0e236043cbca)

2. 不开代理不能翻译？哪个服务？如果开代理能访问，说明接入的服务没问题，即软件功能正常！另外，谁说可以离线翻译了？谁说的找他负责去
