### ISSUE TITLE
建议增加这个接口，免费的

### ISSUE THREAD

**Issue by nop4LOL** [ZGGSONG/STranslate#87]
https://cloud.baidu.com/doc/WENXINWORKSHOP/s/4lilb2lpf

百度千帆大模型，纯免费

**Comment by ZGGSONG** [comment]
> https://cloud.baidu.com/doc/WENXINWORKSHOP/s/4lilb2lpf
> 
> 
> 
> 百度千帆大模型，纯免费

34a93bf31737d18a4458f9bdeb14e93119d2b056
