### ISSUE TITLE
PaddleOCR 显示：OCR失败，离线数据不完整

### ISSUE THREAD

**Issue by RXUARJ** [ZGGSONG/STranslate#89]
从scoop下载的，OCR服务里，点下载数据包之后，显示加载数据包成功，再点检查数据包显示数据缺失

**Comment by ZGGSONG** [comment]
> 从scoop下载的，OCR服务里，点下载数据包之后，显示加载数据包成功，再点检查数据包显示数据缺失

软件根目录有一个cleanocr.bat退出软件执行完再打开软件重新下载试试。

**Comment by RXUARJ** [comment]
> > 从scoop下载的，OCR服务里，点下载数据包之后，显示加载数据包成功，再点检查数据包显示数据缺失
> 
> 软件根目录有一个cleanocr.bat退出软件执行完再打开软件重新下载试试。

能用了，谢谢
