### ISSUE TITLE
希望增加一个openai的api接口

### ISSUE THREAD

**Issue by Machnlea** [ZGGSONG/STranslate#9]

**Comment by ZGGSONG** [comment]
![openaidemo](https://github.com/ZGGSONG/STranslate/assets/49741009/8ef6db59-338b-41db-818b-7cbf9b035838)

再优化一下打包

**Comment by ZGGSONG** [comment]
closes [1.0.3.118](https://github.com/ZGGSONG/STranslate/releases/tag/1.0.3.118)
