### ISSUE TITLE
界面样式优化请求

### ISSUE THREAD

**Issue by watchingfun** [ZGGSONG/STranslate#91]
目前设置界面是有边框阴影的，但是翻页界面没有边框阴影，希望统一一下，如果可能的话，希望推出亚克力效果

**Comment by ZGGSONG** [comment]
> 目前设置界面是有边框阴影的，但是翻页界面没有边框阴影，希望统一一下，如果可能的话，希望推出亚克力效果

1. 翻译界面没有是因为我在使用与设置界面相同的方案去实现翻译界面时发现与动画搭配有点问题，效果不及预期。这部分我后面再看看能不能有别的方法优化出来
2. 云母效果那个我之前也研究过/笑哭，没出结果就被别的事耽搁了。这个我个人也是先比较喜欢的，等着吧   我再研究研究

**Comment by ZGGSONG** [comment]
云母、亚克力那个改的style太多了，而且效果一言难尽，做着做着感觉ui整个都重构了，先放那以后有时间在写吧😅
