### ISSUE TITLE
优化建议

### ISSUE THREAD

**Issue by nop4LOL** [ZGGSONG/STranslate#92]
复制按钮，能不能放到最右边，这样方便用户操作，不然每次复制，鼠标都要移动到很前面，十分不方便。

![image](https://github.com/ZGGSONG/STranslate/assets/117899311/392c8ce1-80a1-46fc-b11f-dd545f1f61c3)

**Comment by ZGGSONG** [comment]
软件现在支持热键快捷复制，Ctrl+1-8复制第一到第八个服务的结果，Ctrl+9复制最后一条结果

**Comment by nop4LOL** [comment]
> 软件现在支持热键快捷复制，Ctrl+1-8复制第一到第八个服务的结果，Ctrl+9复制最后一条结果

快捷键太麻烦了，手指没那么长，按一次ctrl+4 都费劲~~~~呜呜呜~~~如果放到右边来，鼠标操作会轻松超级多
