### ISSUE TITLE
没有联网，没办法使用本地的 STranslate

### ISSUE THREAD

**Issue by boxstudy** [ZGGSONG/STranslate#94]
在没有联网的时候，没有办法直接使用本地的 STranslate。

会产生错误

请求出错：No such host is known
(www2.deepl.com:443)

<img width="959" alt="image" src="https://github.com/ZGGSONG/STranslate/assets/63934175/0be0e8a3-3646-44e9-9f69-eb6ab4435f6c">

**Comment by ZGGSONG** [comment]
翻新没有离线的！本地服务只是自带一个访问远端服务且无需配置的内置翻译服务

**Comment by ZGGSONG** [comment]
软件是带离线ocr
