### ISSUE TITLE
新发展方向建议

### ISSUE THREAD

**Issue by nop4LOL** [ZGGSONG/STranslate#95]
ST既然能集合AI引擎做成翻译，那么直接在原有的代码上修改一下，做成一个支持多个模型的AI客户端不也是可以的吗？这样就可以很方便直接调出来问问题了，而不仅仅是翻译。

目前市场痛点：

1、大部分集成AI的软件都是chromium或者wv2内核，纯屎山，要么就是需要浏览器打开某个在线网址去填写api。

**Comment by ZGGSONG** [comment]
那都可以拉出来开个新项目，你有没有兴趣来一起做一做/斜眼笑

**Comment by nop4LOL** [comment]
> 那都可以拉出来开个新项目，你有没有兴趣来一起做一做/斜眼笑

没问题啊，我可以一起帮忙出点力，加一下我vx：zaijian
