### ISSUE TITLE
建议划词翻译增加”替换划词选中的文本“功能

### ISSUE THREAD

**Issue by GEEKCX** [ZGGSONG/STranslate#97]
![image](https://github.com/ZGGSONG/STranslate/assets/31879429/3c3fe5fe-eb24-4ffb-bb1e-3fdd7b0cc907)

![image](https://github.com/ZGGSONG/STranslate/assets/31879429/256fdea9-e480-444a-9fe5-9e39803e1c54)
类似DeepL客户端中的划词翻译功能——”插入至“

![image](https://github.com/ZGGSONG/STranslate/assets/31879429/a22c4716-51e6-4e5f-84b9-9b9947a12060)
可以给这边加个icon

**Comment by ZGGSONG** [comment]
其实这个功能我正在做/笑哭

**Comment by GEEKCX** [comment]
> 其实这个功能我正在做/笑哭

催更哈哈
