### ISSUE TITLE
希望将欧拉马的提示词更改的按钮放到主界面上.

### ISSUE THREAD

**Issue by Chadli2022** [ZGGSONG/STranslate#98]
使用欧拉马用千问二作为后端非常的好用但是问题是我需要经常更改提示词以便应用与翻译和对话,经常要到页面设置页面里面去修改挺麻烦的

**Comment by ZGGSONG** [comment]
![image](https://github.com/ZGGSONG/STranslate/assets/49741009/e7c3fdf7-ed88-4a00-ab0f-c91caed0a9f6)

**Comment by xtbggqy** [comment]
> 使用欧拉马用千问二作为后端非常的好用但是问题是我需要经常更改提示词以便应用与翻译和对话,经常要到页面设置页面里面去修改挺麻烦的

你好，我想问下你使用ollama会遇到“请求超时: The request was canceled due to the configured HttpClient.Timeout of 10 seconds elapsing.”

**Comment by ZGGSONG** [comment]
这就是服务无法访问
