### ISSUE TITLE
发现热键截图翻译在截图后没识别任何内容

### ISSUE THREAD

**Issue by ZGNCZMY** [ZGGSONG/STranslate#99]
目前用的是最新的1.1.4.523 self_contained
Windows版本：Windows11 22631.3593
![STranslate](https://github.com/ZGGSONG/STranslate/assets/26360517/7502c9a2-4bc7-44c6-8487-763e87cd48e0)

**Comment by ZGGSONG** [comment]
软件根目录有个logs目录，你看下日志里面的内容，可以贴出来我看看

另外发现loading动画在主界面又placeholder时可以优化🤣

**Comment by ZGNCZMY** [comment]
> 软件根目录有个logs目录，你看下日志里面的内容，可以贴出来我看看
> 
> 另外发现loading动画在主界面又placeholder时可以优化🤣

2024-06-19 01:30:36.270 [INF] STranslate_1.1.4.523[Administrator] Opened...
2024-06-19 01:42:57.903 [ERR] [STranslate(565b1faf-7a3b-408a-8301-7188157d27e4)] 请求出错, 请求API: , 异常信息: 不知道这样的主机。 (www2.deepl.com:443)
2024-06-19 01:50:26.419 [ERR] [STranslate(565b1faf-7a3b-408a-8301-7188157d27e4)] 请求出错, 请求API: , 异常信息: 不知道这样的主机。 (www2.deepl.com:443)
2024-06-19 07:07:14.824 [INF] STranslate_1.1.4.523[Administrator] Closed...

2024-06-19 07:08:13.410 [INF] STranslate_1.1.4.523[Administrator] Opened...
2024-06-19 20:07:21.520 [INF] STranslate_1.1.4.523[Administrator] Opened...

**Comment by ZGNCZMY** [comment]
> 软件根目录有个logs目录，你看下日志里面的内容，可以贴出来我看看
> 
> 另外发现loading动画在主界面又placeholder时可以优化🤣

除了网络问题以外似乎看不出明显的error

**Comment by ZGGSONG** [comment]
这个问题是稳定触发嘛

**Comment by ZGNCZMY** [comment]
> 这个问题是稳定触发嘛

肥肠稳定的bug，哈哈

**Comment by ZGGSONG** [comment]
这  我无法复现    你这个情况  我真没见过  我看了一下代码   热键和点击触发其实调的是同一个函数

![动画](https://github.com/ZGGSONG/STranslate/assets/49741009/a206d2ad-a2ce-4ce0-b7e4-e72fbd2c5f58)

**Comment by ZGNCZMY** [comment]
> 这 我无法复现 你这个情况 我真没见过 我看了一下代码 热键和点击触发其实调的是同一个函数
> 
> ![动画](https://private-user-images.githubusercontent.com/49741009/341355919-a206d2ad-a2ce-4ce0-b7e4-e72fbd2c5f58.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NzYwNTUsIm5iZiI6MTcxODg3NTc1NSwicGF0aCI6Ii80OTc0MTAwOS8zNDEzNTU5MTktYTIwNmQyYWQtYTJjZS00Y2UwLWI3ZTQtZTcyZmJkMmM1ZjU4LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDA5MjkxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwZTVmMDIyMDE3NjkyNzc1NDczZjQ1MTM0YTQwYWE5ZDJkNThhZTE4MmViYWZkODYzZjZjMzgzOThhMWJjNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MD-ivf3o2sdZq7Ny3-FUsR8-UsN398vLZUGO-T-5W9A) [ ![动画](https://private-user-images.githubusercontent.com/49741009/341355919-a206d2ad-a2ce-4ce0-b7e4-e72fbd2c5f58.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NzYwNTUsIm5iZiI6MTcxODg3NTc1NSwicGF0aCI6Ii80OTc0MTAwOS8zNDEzNTU5MTktYTIwNmQyYWQtYTJjZS00Y2UwLWI3ZTQtZTcyZmJkMmM1ZjU4LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDA5MjkxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwZTVmMDIyMDE3NjkyNzc1NDczZjQ1MTM0YTQwYWE5ZDJkNThhZTE4MmViYWZkODYzZjZjMzgzOThhMWJjNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MD-ivf3o2sdZq7Ny3-FUsR8-UsN398vLZUGO-T-5W9A) ](https://private-user-images.githubusercontent.com/49741009/341355919-a206d2ad-a2ce-4ce0-b7e4-e72fbd2c5f58.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NzYwNTUsIm5iZiI6MTcxODg3NTc1NSwicGF0aCI6Ii80OTc0MTAwOS8zNDEzNTU5MTktYTIwNmQyYWQtYTJjZS00Y2UwLWI3ZTQtZTcyZmJkMmM1ZjU4LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDA5MjkxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwZTVmMDIyMDE3NjkyNzc1NDczZjQ1MTM0YTQwYWE5ZDJkNThhZTE4MmViYWZkODYzZjZjMzgzOThhMWJjNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MD-ivf3o2sdZq7Ny3-FUsR8-UsN398vLZUGO-T-5W9A) [ ](https://private-user-images.githubusercontent.com/49741009/341355919-a206d2ad-a2ce-4ce0-b7e4-e72fbd2c5f58.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NzYwNTUsIm5iZiI6MTcxODg3NTc1NSwicGF0aCI6Ii80OTc0MTAwOS8zNDEzNTU5MTktYTIwNmQyYWQtYTJjZS00Y2UwLWI3ZTQtZTcyZmJkMmM1ZjU4LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDA5MjkxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwZTVmMDIyMDE3NjkyNzc1NDczZjQ1MTM0YTQwYWE5ZDJkNThhZTE4MmViYWZkODYzZjZjMzgzOThhMWJjNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MD-ivf3o2sdZq7Ny3-FUsR8-UsN398vLZUGO-T-5W9A)

![image](https://github.com/ZGGSONG/STranslate/assets/26360517/3d400c81-3f32-4456-8b2f-71e60a9b06b8)
微信
![image](https://github.com/ZGGSONG/STranslate/assets/26360517/76b6977b-bb99-48a8-8794-cb11afd37774)
QQ
![image](https://github.com/ZGGSONG/STranslate/assets/26360517/15a60e59-34ef-4ab7-8112-be65fb387938)
系统自带
在用的聊天软件都没冲突的，我也是一头雾水

**Comment by ZGGSONG** [comment]
你热键能调用触发功能就说明你的热键功能正常，我猜测可能跟独立发布有点关系  你可以试试下载无runtime的版本试试，打开的时候会提示你下载runtime这个runtime也就几十兆 最后加起来肯定比selfcontained版本小 那个版本没有听过有这个问题  主要是没有办法定位  除非我加日志   你来帮我测试一下 哈哈哈哈哈哈

**Comment by ZGNCZMY** [comment]
> 你热键能调用触发功能就说明你的热键功能正常，我猜测可能跟独立发布有点关系 你可以试试下载无runtime的版本试试，打开的时候会提示你下载runtime这个runtime也就几十兆 最后加起来肯定比selfcontained版本小 那个版本没有听过有这个问题 主要是没有办法定位 除非我加日志 你来帮我测试一下 哈哈哈哈哈哈

好的，我先试试无runtime版本，建议下版本日志输出完整点-，现在的logs里面没东西的，遇到问题发出来也不好定位

**Comment by ZGNCZMY** [comment]
> 你热键能调用触发功能就说明你的热键功能正常，我猜测可能跟独立发布有点关系 你可以试试下载无runtime的版本试试，打开的时候会提示你下载runtime这个runtime也就几十兆 最后加起来肯定比selfcontained版本小 那个版本没有听过有这个问题 主要是没有办法定位 除非我加日志 你来帮我测试一下 哈哈哈哈哈哈

无runtime版本暂时没发现这个问题

**Comment by ZGGSONG** [comment]
> > 你热键能调用触发功能就说明你的热键功能正常，我猜测可能跟独立发布有点关系 你可以试试下载无runtime的版本试试，打开的时候会提示你下载runtime这个runtime也就几十兆 最后加起来肯定比selfcontained版本小 那个版本没有听过有这个问题 主要是没有办法定位 除非我加日志 你来帮我测试一下 哈哈哈哈哈哈
> 
> 
> 
> 好的，我先试试无runtime版本，建议下版本日志输出完整点-，现在的logs里面没东西的，遇到问题发出来也不好定位

是的，主要是那些地方代码部分一般不会出错，也没想着打日志，不然打日志的地方可太多了，并且selfcontained版本属于微软自己的优化，可能.net8针对这部分存在一些问题吧，优先选择带runtime的版本，毕竟在这个上面开发的，有问题也基本都体现出来了

**Comment by ZGNCZMY** [comment]
> > > 你热键能调用触发功能就说明你的热键功能正常，我猜测可能跟独立发布有点关系 你可以试试下载无runtime的版本试试，打开的时候会提示你下载runtime这个runtime也就几十兆 最后加起来肯定比selfcontained版本小 那个版本没有听过有这个问题 主要是没有办法定位 除非我加日志 你来帮我测试一下 哈哈哈哈哈哈
> > 
> > 
> > 好的，我先试试无runtime版本，建议下版本日志输出完整点-，现在的logs里面没东西的，遇到问题发出来也不好定位
> 
> 是的，主要是那些地方代码部分一般不会出错，也没想着打日志，不然打日志的地方可太多了，并且selfcontained版本属于微软自己的优化，可能.net8针对这部分存在一些问题吧，优先选择带runtime的版本，毕竟在这个上面开发的，有问题也基本都体现出来了

我测试了下，在呼出程序窗口显示的时候热键就没问题
